import type { FamilySummary, FamilyDTO, MemberDTO, VirtualDTO, ExitInput, TransferInput, ExitPreview, TransferPreview } from "@family-todo/contracts";
import { familyApi, listFamilies, listManagedVirtualMembers, previewExit, previewTransfer } from "../../services/family-api";
import { PersonalApiError, isAccessDenied } from "../../services/personal-api";
import { back, errorMessage, navigationMetrics, readySession } from "../../services/personal-view";
Page({
  data:{statusHeight:0,navHeight:44,capsuleWidth:100,status:"loading",error:"",families:[] as FamilySummary[],id:"",family:null as FamilyDTO|null,members:[] as MemberDTO[],virtualMembers:[] as VirtualDTO[],owner:false,ownerName:"",sheet:"",name:"",myName:"",formTitle:"",writing:false,uncertain:false,previewLoading:false,exit:null as ExitPreview|null,transfer:null as TransferPreview|null,targets:[] as MemberDTO[],targetIndex:0,previewError:""},
  alive:true,visible:false,epoch:0,editId:"",editVersion:0,exitInput:null as ExitInput|null,transferInput:null as TransferInput|null,pending:null as (()=>Promise<unknown>)|null,
  onLoad(query:Record<string,string|undefined>){this.setData({...navigationMetrics(),id:query.id??""});},
  onShow(){this.visible=true;void this.load();},onHide(){this.visible=false;this.epoch++;},onUnload(){this.alive=false;this.visible=false;this.epoch++;},back,
  async load(){if(this.pending)return;const epoch=++this.epoch;this.setData({status:"loading",error:"",family:null,members:[],virtualMembers:[],exit:null,transfer:null,previewLoading:false,sheet:""});try{await readySession();const result=await listFamilies();const id=result.items.some(f=>f.id===this.data.id)?this.data.id:"";let detail=null;let virtualMembers:VirtualDTO[]=[];if(id){detail=await familyApi.read("family.get",{id});virtualMembers=detail.virtualMembers;if(detail.family.myMembershipId===detail.family.ownerMembershipId){virtualMembers=await listManagedVirtualMembers(id);}}if(!this.visible||epoch!==this.epoch)return;this.setData({status:result.items.length?"ready":"empty",families:result.items,id,family:detail?.family??null,members:detail?.members??[],virtualMembers,owner:detail?.family.myMembershipId===detail?.family.ownerMembershipId&&!!detail,ownerName:detail?.members.find(m=>m.role==="owner")?.name??"",targets:detail?.members.filter(m=>!m.isMe)??[]});}catch(error){if(this.alive&&epoch===this.epoch){if(isAccessDenied(error))this.clearCurrentFamily();this.setData({status:"error",error:errorMessage(error),family:null,members:[],virtualMembers:[],sheet:""});}}},
  select(e:WechatMiniprogram.TouchEvent){const id:unknown=e.currentTarget.dataset.id;if(typeof id!=="string"||this.pending)return;this.setData({id});void this.load();},
  allFamilies(){this.setData({id:""});void this.load();},
  join(){wx.navigateTo({url:"/pages/invitation/index"});},
  invite(){wx.navigateTo({url:`/pages/invitation/index?familyId=${this.data.id}`});},
  openCreate(){this.setData({sheet:"create",formTitle:this.data.families.length?"创建另一个家庭":"创建家庭",name:"",myName:"",error:""});},
  renameFamily(){const f=this.data.family;if(!f||!this.data.owner)return;this.editId=f.id;this.editVersion=f.version;this.setData({sheet:"family",formTitle:"修改家庭名称",name:f.name,error:""});},
  renameMember(e:WechatMiniprogram.TouchEvent){const member=this.data.members.find(m=>m.id===e.currentTarget.dataset.id);if(!member||(!member.isMe&&!this.data.owner))return;this.editId=member.id;this.editVersion=member.version;this.setData({sheet:"member",formTitle:"修改称呼",name:member.name,error:""});},
  addVirtual(){if(this.data.owner)this.setData({sheet:"addVirtual",formTitle:"添加无账号成员",name:"",error:""});},
  renameVirtual(e:WechatMiniprogram.TouchEvent){const member=this.data.virtualMembers.find(m=>m.id===e.currentTarget.dataset.id);if(!member||!this.data.owner)return;this.editId=member.id;this.editVersion=member.version;this.setData({sheet:"virtual",formTitle:"修改称呼",name:member.name,error:""});},
  nameInput(e:WechatMiniprogram.Input){this.setData({name:e.detail.value});},myNameInput(e:WechatMiniprogram.Input){this.setData({myName:e.detail.value});},noop(){},
  closeSheet(){if(this.data.writing||this.data.uncertain||this.data.previewLoading)return;this.setData({sheet:"",error:"",previewError:"",exit:null,transfer:null});},
  async run(run:()=>Promise<unknown>){if(this.data.writing)return;this.pending??=run;this.setData({writing:true,error:""});try{await this.pending();this.pending=null;if(this.alive){this.setData({uncertain:false,sheet:""});await this.load();}}catch(error){const uncertain=error instanceof PersonalApiError&&error.retryable;if(!uncertain)this.pending=null;if(this.alive){if(isAccessDenied(error))this.clearCurrentFamily();this.setData({uncertain,error:error instanceof PersonalApiError&&error.code==="PREVIEW_EXPIRED"?"预览已过期，请重新查看交接影响。":errorMessage(error),...(error instanceof PersonalApiError&&error.code==="PREVIEW_EXPIRED"?{exit:null,transfer:null}:{})});}}finally{if(this.alive)this.setData({writing:false});}},
  clearCurrentFamily(){const id=this.data.id;this.epoch++;this.editId="";this.editVersion=0;this.exitInput=null;this.transferInput=null;this.setData({status:"error",id:"",family:null,members:[],virtualMembers:[],families:this.data.families.filter(family=>family.id!==id),owner:false,ownerName:"",targets:[],targetIndex:0,sheet:"",name:"",myName:"",formTitle:"",exit:null,transfer:null,previewLoading:false,previewError:""});},
  retryWrite(){if(this.pending)void this.run(this.pending);},
  async save(){const name=this.data.name.trim();if(!name||[...name].length>(this.data.sheet==="create"||this.data.sheet==="family"?24:12)){this.setData({error:"请填写有效的名称或称呼。"});return;}const f=this.data.family;const ref={id:this.editId,expectedVersion:this.editVersion,name};switch(this.data.sheet){case "create":{const myName=this.data.myName.trim();if(!myName||[...myName].length>12){this.setData({error:"请填写 1–12 个字的家庭称呼。"});return;}await this.run(async()=>{const result=await familyApi.write("family.create",{name,myName});if(this.alive)this.setData({id:result.family.id});});break;}case "family":await this.run(()=>familyApi.write("family.update",ref));break;case "member":await this.run(()=>familyApi.write("member.rename",ref));break;case "virtual":await this.run(()=>familyApi.write("virtualMember.update",ref));break;case "addVirtual":if(f){const input={familyId:f.id,expectedFamilyVersion:f.version,name};await this.run(()=>familyApi.write("virtualMember.create",input));}break;}},
  async deactivate(e:WechatMiniprogram.TouchEvent){const member=this.data.virtualMembers.find(m=>m.id===e.currentTarget.dataset.id);if(!member||!this.data.owner)return;const answer=await wx.showModal({title:"停用这位无账号成员？",content:"历史记录保留，未结束事项继续由拥有人管理。",confirmText:"确认停用"});if(!answer.confirm||!this.visible)return;const input={id:member.id,expectedVersion:member.version};await this.run(()=>familyApi.write("virtualMember.deactivate",input));},
  startTransfer(){if(!this.data.owner)return;if(!this.data.targets.length){this.setData({sheet:"noSuccessor",formTitle:"还没有可承接的家人"});return;}this.setData({sheet:"transfer",formTitle:"转交家庭拥有权",transfer:null,exit:null,targetIndex:0,previewError:""});void this.loadTransfer();},
  targetChange(e:WechatMiniprogram.PickerChange){if(this.pending||this.data.previewLoading)return;this.setData({targetIndex:Number(e.detail.value),transfer:null});void this.loadTransfer();},
  async loadTransfer(){const target=this.data.targets[this.data.targetIndex];if(!target||this.pending)return;this.transferInput={familyId:this.data.id,toMembershipId:target.id};const input=this.transferInput;const epoch=++this.epoch;this.setData({previewLoading:true,previewError:"",transfer:null});try{const result=await previewTransfer(input);if(this.visible&&epoch===this.epoch)this.setData({transfer:result});}catch(error){if(this.alive&&epoch===this.epoch){if(isAccessDenied(error)){this.clearCurrentFamily();this.setData({error:errorMessage(error)});}else if(this.visible)this.setData({previewError:errorMessage(error)});}}finally{if(this.visible&&epoch===this.epoch)this.setData({previewLoading:false});}},
  startExit(e:WechatMiniprogram.TouchEvent){const f=this.data.family;if(!f)return;const id:unknown=e.currentTarget.dataset.id;const target=this.data.members.find(m=>m.id===(typeof id==="string"?id:f.myMembershipId));if(!target)return;if(target.role==="owner"){this.startTransfer();return;}this.exitInput={familyId:f.id,targetMembershipId:target.id,mode:target.isMe?"leave":"remove"};this.setData({sheet:"exit",formTitle:target.isMe?"确认退出这个家庭？":"确认移除这位家人？",exit:null,transfer:null});void this.loadExit();},
  async loadExit(){if(!this.exitInput||this.pending)return;const input=this.exitInput;const epoch=++this.epoch;this.setData({previewLoading:true,previewError:"",exit:null});try{const result=await previewExit(input);if(this.visible&&epoch===this.epoch)this.setData({exit:result});}catch(error){if(this.alive&&epoch===this.epoch){if(isAccessDenied(error)){this.clearCurrentFamily();this.setData({error:errorMessage(error)});}else if(this.visible)this.setData({previewError:errorMessage(error)});}}finally{if(this.visible&&epoch===this.epoch)this.setData({previewLoading:false});}},
  async confirmExit(){const preview=this.data.exit;if(!preview||!this.exitInput||this.data.previewLoading)return;const input={...this.exitInput,previewToken:preview.previewToken,expectedFamilyVersion:preview.familyVersion};await this.run(async()=>{await familyApi.write("family.exit",input);if(input.mode==="leave"&&this.alive)this.setData({id:"",family:null,members:[],virtualMembers:[]});});},
  async confirmTransfer(){const preview=this.data.transfer;if(!preview||!this.transferInput||this.data.previewLoading)return;const input={...this.transferInput,previewToken:preview.previewToken,expectedFamilyVersion:preview.familyVersion};await this.run(async()=>{await familyApi.write("family.transferOwnership",input);if(this.alive)wx.showToast({title:"拥有权已转交；退出需另行确认",icon:"none"});});},
});
