import type { FamilySummary, PersonalDraft, TaskDTO, Subject, OccurrenceDTO, ParticipantDTO } from "@family-todo/contracts";
import { personalApi, PersonalApiError } from "../../services/personal-api";
import { familyApi, listFamilies } from "../../services/family-api";
import { accessInput, permissionRows, subjectKey, subjectNotice, subjectOptions, taskSubject, withoutViewer } from "../../services/collaboration-draft";
import type { PermissionRow, Roster, SubjectOption } from "../../services/collaboration-draft";
import { back, dateAt, errorMessage, navigationMetrics, readySession } from "../../services/personal-view";
Page({
  data:{statusHeight:0,navHeight:44,capsuleWidth:100,status:"loading",error:"",id:"",version:0,title:"",note:"",date:"",time:"",remindMe:true,saving:false,uncertain:false,conflict:false,latest:null as TaskDTO|null,success:"",families:[] as FamilySummary[],familyOptions:["个人事项"],familyIndex:0,familyLocked:false,subjectOptions:[] as SubjectOption[],subjectNames:["自己"],subjectIndex:0,rows:[] as PermissionRow[],notice:"个人事项仅自己可见。",scheduleLocked:false,subjectMetadataMissing:false,shareOnly:false},
  alive:true,epoch:0,pendingDraft:null as PersonalDraft|null,task:null as TaskDTO|null,occurrence:null as OccurrenceDTO|null,roster:null as Roster|null,subject:{kind:"self"} as Subject,initialFamily:"",
  onLoad(query:Record<string,string|undefined>){this.initialFamily=query.familyId??"";this.setData({...navigationMetrics(),id:query.id??"",shareOnly:query.share==="1"});void this.load();},onUnload(){this.alive=false;this.epoch++;},
  back(){if(this.data.saving||this.data.uncertain){wx.showToast({title:"请先重试确认保存结果",icon:"none"});return;}back();},
  async load(){const epoch=++this.epoch;this.setData({status:"loading",error:"",rows:[]});try{await readySession();const families=await listFamilies();let task:TaskDTO|null=null;let occurrence:OccurrenceDTO|null=null;let date="";if(this.data.id){const result=await personalApi.read("task.get",{id:this.data.id});task=result.task;occurrence=result.occurrence;if(!(this.data.shareOnly?task.capabilities.canShare:task.capabilities.canEdit))throw new Error("你已没有修改这份安排的权限。");}else{date=dateAt((await personalApi.read("task.list",{limit:1})).asOf);}const familyId=task?.familyId??this.initialFamily;const roster=familyId?await familyApi.read("family.get",{id:familyId}):null;if(!this.alive||epoch!==this.epoch)return;this.task=task;this.occurrence=occurrence;this.roster=roster;this.subject=task?taskSubject(task):roster?{kind:"member",membershipId:roster.family.myMembershipId}:{kind:"self"};this.setData({status:"ready",families:families.items,familyOptions:["个人事项",...families.items.map(f=>f.name)],familyIndex:familyId?families.items.findIndex(f=>f.id===familyId)+1:0,familyLocked:!!task?.familyId,subjectMetadataMissing:!!task?.familyId&&task.participants.some(row=>row.isCreatorManager===undefined),version:task?.version??0,title:task?.title??"",note:task?.note??"",date:task?.schedule.date??date,time:task?.schedule.time??"",remindMe:task?.myReminder.enabled??true,scheduleLocked:!!occurrence&&occurrence.status!=="pending"});this.updateRoster(task?.participants);}catch(error){if(this.alive&&epoch===this.epoch){this.task=null;this.roster=null;this.setData({status:"error",error:errorMessage(error),rows:[],title:"",note:""});}}},
  updateRoster(previous?:ParticipantDTO[]){let options=this.roster?subjectOptions(this.roster):[{name:"自己",subject:{kind:"self" as const}}];if(!options.some(o=>subjectKey(o.subject)===subjectKey(this.subject))&&this.task)options=[...options,{name:`${this.task.subjectName} · 原执行对象`,subject:this.subject}];this.setData({subjectOptions:options,subjectNames:options.map(o=>o.name),subjectIndex:Math.max(0,options.findIndex(o=>subjectKey(o.subject)===subjectKey(this.subject))),rows:this.roster?permissionRows(this.roster,this.subject,previous??this.data.rows,!!this.task?.familyId):[],notice:subjectNotice(this.subject,this.roster)});},
  async familyChange(e:WechatMiniprogram.PickerChange){if(this.data.familyLocked||this.data.uncertain||this.data.saving)return;const index=Number(e.detail.value);const family=this.data.families[index-1];const epoch=++this.epoch;this.setData({status:"loading",rows:[],error:""});this.roster=null;try{const roster=family?await familyApi.read("family.get",{id:family.id}):null;if(!this.alive||epoch!==this.epoch)return;this.roster=roster;this.subject=roster?{kind:"member",membershipId:roster.family.myMembershipId}:{kind:"self"};this.setData({familyIndex:index,status:"ready"});this.updateRoster([]);}catch(error){if(this.alive&&epoch===this.epoch)this.setData({status:"error",error:errorMessage(error)});}},
  async subjectChange(e:WechatMiniprogram.PickerChange){if(this.data.subjectMetadataMissing){this.setData({error:"管理身份信息需要更新，请重新加载后再更换执行对象。"});return;}if(this.data.scheduleLocked||this.data.shareOnly||this.data.saving||this.data.uncertain)return;const option=this.data.subjectOptions[Number(e.detail.value)];if(!option)return;if(this.task){const answer=await wx.showModal({title:"更换执行对象",content:`${subjectNotice(option.subject,this.roster)} 历史记录保留原执行对象。管理范围可能随执行对象改变。`,confirmText:"确认更换"});if(!answer.confirm||!this.alive)return;}this.subject=option.subject;this.updateRoster();},
  async permissionChange(e:WechatMiniprogram.CheckboxGroupChange){if(this.data.uncertain||this.data.saving)return;const id:unknown=e.currentTarget.dataset.id;const field:unknown=e.currentTarget.dataset.field;const row=this.data.rows.find(r=>r.membershipId===id);if(!row)return;const checked=e.detail.value.includes("yes");let next={...row};if(field==="view"){if(row.requiredViewer)return;if(!checked&&(row.canHelp||row.receivesReminder)){const answer=await wx.showModal({title:"取消查看权限？",content:`${row.name}的代记权限和提醒也会一并取消。`,confirmText:"确认取消"});if(!answer.confirm||!this.alive)return;}next=checked?{...row,canView:true}:withoutViewer(row);}else if(field==="help"){if(!row.canView)return;next.canHelp=checked;}else if(field==="reminder"){if(row.isMe||!row.canView||row.reminderSelfDisabled)return;next.receivesReminder=checked;}else return;this.setData({rows:this.data.rows.map(r=>r.membershipId===id?next:r)});},
  titleInput(e:WechatMiniprogram.Input){this.setData({title:e.detail.value});},noteInput(e:WechatMiniprogram.Input){this.setData({note:e.detail.value});},dateChange(e:WechatMiniprogram.PickerChange){if(!this.data.scheduleLocked&&typeof e.detail.value==="string")this.setData({date:e.detail.value});},timeChange(e:WechatMiniprogram.PickerChange){if(!this.data.scheduleLocked&&typeof e.detail.value==="string")this.setData({time:e.detail.value});},clearDate(){if(!this.data.scheduleLocked)this.setData({date:"",time:""});},clearTime(){if(!this.data.scheduleLocked)this.setData({time:""});},reminderChange(e:WechatMiniprogram.CheckboxGroupChange){this.setData({remindMe:e.detail.value.includes("enabled")});},
  async save(){if(this.data.saving||this.data.conflict)return;if(!this.data.title.trim()){this.setData({error:"先写下要做的事情。"});return;}if(!this.pendingDraft&&this.task&&!this.task.familyId&&this.roster){const answer=await wx.showModal({title:"归属到这个家庭？",content:`这件事将归属「${this.roster.family.name}」，保存后不能迁移到其他家庭或改回个人。${this.data.notice}`,confirmText:"确认归属"});if(!answer.confirm||!this.alive)return;}
    this.pendingDraft??={title:this.data.title,note:this.data.note,familyId:this.roster?.family.id??null,subject:this.subject,schedule:{kind:"once",date:this.data.date||null,time:this.data.time||null},access:accessInput(this.data.rows,this.data.remindMe)};const draft=this.pendingDraft;this.setData({saving:true,error:""});try{const result=this.data.id?(this.data.shareOnly&&this.task?.familyId?await personalApi.write("task.setAccess",{id:this.data.id,expectedVersion:this.data.version,access:draft.access}):await personalApi.write("task.update",{id:this.data.id,expectedVersion:this.data.version,draft})):await personalApi.write("task.create",{draft});this.pendingDraft=null;if(this.alive){this.setData({uncertain:false});wx.showToast({title:"安排已保存",icon:"success"});if("accessLost" in result){this.task=null;this.roster=null;this.setData({rows:[],title:"",note:""});wx.reLaunch({url:"/pages/home/index"});}else back();}}catch(error){if(this.alive){const uncertain=error instanceof PersonalApiError&&error.retryable;if(!uncertain)this.pendingDraft=null;const denied=error instanceof PersonalApiError&&["NOT_FOUND","FORBIDDEN","FAMILY_NOT_FOUND"].includes(error.code);if(denied){this.task=null;this.roster=null;}this.setData({error:errorMessage(error),uncertain,conflict:error instanceof PersonalApiError&&error.code==="VERSION_CONFLICT",...(denied?{status:"error",rows:[],title:"",note:""}:{})});}}finally{if(this.alive)this.setData({saving:false});}},
  async loadLatest(){try{const result=await personalApi.read("task.get",{id:this.data.id});if(!result.task.capabilities.canEdit)throw new Error("你已没有修改权限。");if(this.alive){this.occurrence=result.occurrence;this.setData({latest:result.task});}}catch(error){if(this.alive){this.task=null;this.roster=null;this.setData({status:"error",rows:[],title:"",note:"",error:errorMessage(error)});}}},
  async keepDraft(){const latest=this.data.latest;if(!latest)return;const epoch=++this.epoch;this.setData({status:"loading",rows:[]});try{const roster=latest.familyId?await familyApi.read("family.get",{id:latest.familyId}):null;const families=await listFamilies();if(!this.alive||epoch!==this.epoch)return;this.task=latest;this.roster=roster;this.subject=taskSubject(latest);this.setData({status:"ready",families:families.items,familyOptions:["个人事项",...families.items.map(f=>f.name)],familyIndex:latest.familyId?families.items.findIndex(f=>f.id===latest.familyId)+1:0,familyLocked:!!latest.familyId,subjectMetadataMissing:!!latest.familyId&&latest.participants.some(row=>row.isCreatorManager===undefined),version:latest.version,conflict:false,error:"已保留标题和备注；执行对象、日程及权限已更新，请核对后重新保存。",latest:null,date:latest.schedule.date??"",time:latest.schedule.time??"",remindMe:latest.myReminder.enabled,scheduleLocked:!!this.occurrence&&this.occurrence.status!=="pending"});this.updateRoster(latest.participants);}catch(error){if(this.alive&&epoch===this.epoch){this.task=null;this.roster=null;this.setData({status:"error",rows:[],title:"",note:"",error:errorMessage(error)});}}},
  another(){wx.navigateTo({url:"/pages/editor/index"});},
});
