import { applyNativeData } from "../../tests/helpers/native-data";
import { randomUUID } from "node:crypto";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import type { TaskDTO } from "@family-todo/contracts";
import type { DraftInput } from "../services/input-recovery";
type NativePage=Record<string,unknown>&{data:Record<string,unknown>;setData:(patch:Record<string,unknown>)=>void};
let page:NativePage;
let storage:Map<string,unknown>;
const user=randomUUID(),id=randomUUID();
const defaultFamily={id:randomUUID(),name:"家",ownerName:"我",myMembershipId:randomUUID(),myRole:"owner" as const,version:1};
const input:DraftInput={title:"",note:"未完成输入",familyId:null,subject:{kind:"self"},viewers:[],remindMe:false,repeat:"daily",date:"2026-09-14",time:"",endDate:"",times:[""],weekdays:[]};
const task:TaskDTO={id,version:2,title:"最新标题",note:"最新备注",familyId:null,familyName:null,ownerUserId:user,ownerName:"我",createdByUserId:user,subject:{kind:"user",userId:user},subjectName:"我",schedule:{kind:"once",date:null,time:null},participants:[],myReminder:{enabled:false,version:2,selfDisabled:true},lifecycle:"active",createdAt:"2026-09-14T00:00:00.000Z",updatedAt:"2026-09-14T00:00:00.000Z",capabilities:{canEdit:true,canShare:true,canDelete:true,canRestore:false,canRecord:true,canResume:false}};
async function invoke(name:string,...args:unknown[]){const fn=page[name];if(typeof fn!=="function")throw new Error(name);await fn.apply(page,args);}
async function setup(){const api=(await import("../services/personal-api")).personalApi;api.bindRecovery("test",user);vi.spyOn(await import("../services/request-id"),"createRequestId").mockImplementation(async()=>randomUUID());vi.spyOn(await import("../services/family-api"),"listFamilies").mockResolvedValue({items:[defaultFamily],last:{items:[defaultFamily],nextCursor:null,complete:true,asOf:"2026-09-14T00:00:00.000Z"}});vi.spyOn(api,"read").mockImplementation((async(action:string)=>action==="family.get"?{family:defaultFamily,members:[],virtualMembers:[]}:action==="task.get"?{task,occurrence:null}:action==="task.list"?{asOf:"2026-09-14T00:00:00.000Z"}:{nextOccurrences:[],explanation:"",excludedPastSlots:false}) as typeof api.read);return api;}
async function seed(target="editor:new:0",value=input,version=0){const {InputRecovery}=await import("../services/input-recovery");const recovery=new InputRecovery(target);if(recovery.load())recovery.remove();await recovery.start();recovery.save(value,version);return recovery;}
beforeEach(()=>{vi.resetModules();storage=new Map();vi.stubGlobal("wx",{getStorageSync:vi.fn((key:string)=>storage.get(key)),setStorageSync:vi.fn((key:string,value:unknown)=>storage.set(key,structuredClone(value))),removeStorageSync:vi.fn((key:string)=>storage.delete(key)),showModal:vi.fn().mockResolvedValue({confirm:true}),showToast:vi.fn(),switchTab:vi.fn(),navigateTo:vi.fn(),navigateBack:vi.fn(),reLaunch:vi.fn()});vi.stubGlobal("getCurrentPages",()=>[{},{}]);vi.stubGlobal("getApp",()=>({globalData:{session:{ensure:async()=>({id:user})}}}));vi.stubGlobal("Page",(value:NativePage)=>{page=value;page.setData=patch=>applyNativeData(page.data, patch);});});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
it("restores invalid raw fields after rebuilding modules without committing a task",async()=>{await setup();await seed();vi.resetModules();const api=await setup();const write=vi.spyOn(api,"write");await import("./editor/index");await invoke("load");expect(page.data).toMatchObject({title:"",note:"未完成输入",times:[""],repeat:"daily",remindMe:false});expect(write).not.toHaveBeenCalled();});
it("input edits persist immediately, keep on back and discard on next entry",async()=>{await setup();await import("./editor/index");await invoke("load");await invoke("noteInput",{detail:{value:"只填写备注"}});expect([...storage.values()]).toContainEqual(expect.objectContaining({input:expect.objectContaining({title:"",note:"只填写备注"})}));await invoke("back");expect(wx.navigateBack).toHaveBeenCalled();vi.mocked(wx.showModal).mockResolvedValue({confirm:false,cancel:true,errMsg:"ok"});await invoke("load");expect([...storage.keys()].filter(k=>k.includes(":input:"))).toEqual([]);expect(page.data.note).toBe("");});
it("storage failure reports unpersisted input and prevents leaving or sending",async()=>{const api=await setup();await import("./editor/index");await invoke("load");vi.mocked(wx.setStorageSync).mockImplementation(()=>{throw new Error("quota");});await invoke("titleInput",{detail:{value:"事项"}});expect(page.data.error).toContain("尚未可靠保留");await invoke("back");expect(wx.navigateBack).not.toHaveBeenCalled();const write=vi.spyOn(api,"write");await invoke("save");expect(write).not.toHaveBeenCalled();});
it("changed version restores title/note only and requires explicit latest merge",async()=>{await setup();await seed(`editor:${id}:0`,{...input,title:"我的标题"},1);await import("./editor/index");page.setData({id});await invoke("load");expect(page.data).toMatchObject({title:"我的标题",conflict:true,repeat:"once"});await invoke("loadLatest");await invoke("keepDraft");expect(page.data).toMatchObject({title:"我的标题",note:input.note,version:2,conflict:false,repeat:"once",remindMe:false});});
it("permission denial removes draft and private form input",async()=>{const api=await setup();await seed(`editor:${id}:0`,{...input,title:"私密"},2);vi.mocked(api.read).mockResolvedValue({task:{...task,capabilities:{...task.capabilities,canEdit:false}},occurrence:null});await import("./editor/index");page.setData({id});await invoke("load");expect(page.data).toMatchObject({status:"error",title:"",note:"",rows:[]});expect([...storage.keys()].filter(k=>k.includes(":input:"))).toEqual([]);});
it("unknown pending cannot become another create after draft restoration",async()=>{const api=await setup();await seed("editor:new:0",{...input,title:"新建",repeat:"once",times:[],date:""});storage.set(api.recoveryContext+":pending",{version:1,state:"pending",action:"task.create",requestId:randomUUID(),payload:{draft:{title:"新建",note:"",familyId:null,subject:{kind:"self"},schedule:{kind:"once",date:null,time:null},access:{remindMe:true,viewerMembershipIds:[],helperMembershipIds:[],reminderMembershipIds:[]}}}});api.unbindRecovery();api.bindRecovery("test",user);await import("./editor/index");await invoke("load");const write=vi.spyOn(api,"write");await invoke("save");expect(write).not.toHaveBeenCalled();expect(page.data.error).toContain("确认上一次");});
it("completion marker deletes draft before marker and never restores completed input",async()=>{const api=await setup();const recovery=await seed();const draftId=recovery.record?.id;storage.set(api.recoveryContext+":completed:"+draftId,true);await import("./editor/index");await invoke("load");expect(wx.showModal).not.toHaveBeenCalled();const keys=vi.mocked(wx.removeStorageSync).mock.calls.map(c=>c[0]);expect(keys[0]).toContain(":input:");expect(keys[1]).toContain(":completed:");});
it("failed completed-draft removal cannot allow another create",async()=>{const api=await setup();await import("./editor/index");await invoke("load");await invoke("titleInput",{detail:{value:"新建"}});const recovery=page.recovery as {record:{id:string}};storage.set(api.recoveryContext+":completed:"+recovery.record.id,true);vi.mocked(wx.removeStorageSync).mockImplementation(()=>{throw new Error("disk");});const write=vi.spyOn(api,"write");await invoke("save");expect(write).not.toHaveBeenCalled();expect(storage.has(api.recoveryContext+":completed:"+recovery.record.id)).toBe(true);});
it("account generation changes prevent stale unload from touching the new draft",async()=>{const api=await setup();await import("./editor/index");await invoke("load");await invoke("noteInput",{detail:{value:"旧账号"}});api.unbindRecovery();api.bindRecovery("test",user);await seed("editor:new:0",{...input,note:"新会话"});await invoke("onUnload");expect([...storage.values()]).toContainEqual(expect.objectContaining({input:expect.objectContaining({note:"新会话"})}));});
it("quick raw input transfers to full editor using one durable draft id",async()=>{await setup();await import("./home/index");page.setData({today:"2026-09-14",tomorrow:"2026-09-15"});await invoke("openQuick");await invoke("quickNoteInput",{detail:{value:"空标题也能交接"}});const before=[...storage.values()];await invoke("fullEditor");expect(wx.navigateTo).toHaveBeenCalledWith(expect.objectContaining({url:"/pages/editor/index?draft=quick"}));await invoke("onHide");expect([...storage.values()]).toEqual(before);await import("./editor/index");page.recoveryTarget="quick";await invoke("load");expect(page.data.note).toBe("空标题也能交接");expect([...storage.values()]).toEqual(before);});
it("quick draft saved on a previous date goes to editor without changing date",async()=>{await setup();await seed("quick",{...input,repeat:"once",date:"2026-09-12",times:[]});await import("./home/index");page.setData({today:"2026-09-14",tomorrow:"2026-09-15"});await invoke("openQuick");expect(wx.navigateTo).toHaveBeenCalledWith(expect.objectContaining({url:"/pages/editor/index?draft=quick"}));expect([...storage.values()]).toContainEqual(expect.objectContaining({input:expect.objectContaining({date:"2026-09-12"})}));});
it("missing family clears recovery instead of silently creating a personal task",async()=>{await setup();await seed("quick",{...input,familyId:randomUUID()});await import("./home/index");page.setData({today:"2026-09-14"});await invoke("openQuick");expect(page.data).toMatchObject({quickLoading:true,quickTitle:""});expect(page.data.quickError).toContain("原家庭");expect([...storage.keys()].filter(k=>k.includes(":input:"))).toEqual([]);});

it("successful write after page unload still removes its persisted draft",async()=>{const api=await setup();await import("./editor/index");await invoke("load");await invoke("titleInput",{detail:{value:"写入后退出"}});let finish:((value:{task:TaskDTO})=>void)|undefined;vi.spyOn(api,"write").mockImplementation((()=>new Promise<unknown>(resolve=>{finish=resolve;})) as typeof api.write);const saving=invoke("save");await Promise.resolve();await invoke("onUnload");finish?.({task});await saving;expect([...storage.keys()].filter(k=>k.includes(":input:"))).toEqual([]);});
it("current self-disabled reminder wins over restored reminder checkbox",async()=>{await setup();await seed(`editor:${id}:0`,{...input,title:"草稿",remindMe:true},2);await import("./editor/index");page.setData({id});await invoke("load");expect(page.data.remindMe).toBe(false);});
it("malformed raw cache fails closed rather than enabling a new create",async()=>{const api=await setup();storage.set(api.recoveryContext+":input:"+encodeURIComponent("editor:new:0"),{schema:1,id:randomUUID(),version:0,input:{...input,token:"not permitted"}});await import("./editor/index");await invoke("load");expect(page.data.status).toBe("error");expect(page.data.error).toContain("尚未可靠保留");const write=vi.spyOn(api,"write");page.setData({title:"new"});await invoke("save");expect(write).not.toHaveBeenCalled();});

it("home hide then unload cannot overwrite saved family with cleared roster",async()=>{await setup();await import("./home/index");page.setData({today:"2026-09-14",tomorrow:"2026-09-15"});await invoke("openQuick");await invoke("quickNoteInput",{detail:{value:"保留"}});await invoke("onHide");const saved=structuredClone([...storage.entries()]);await invoke("onUnload");expect([...storage.entries()]).toEqual(saved);});

it("editor ignores deferred task data after account switches and clears private fields",async()=>{const api=await setup();let finish:((value:unknown)=>void)|undefined;let started:()=>void=()=>{};const waiting=new Promise<void>(resolve=>{started=resolve;});vi.mocked(api.read).mockImplementation((async(action:string)=>{if(action==="task.get"){started();return new Promise<unknown>(resolve=>{finish=resolve;});}return {nextOccurrences:[]};}) as typeof api.read);await import("./editor/index");page.setData({id,title:"旧私密标题",note:"旧私密备注",families:[{name:"旧家庭"}]});const loading=invoke("load");await waiting;api.bindRecovery("test",randomUUID());finish?.({task,occurrence:null});await loading;expect(page.data).toMatchObject({status:"error",title:"",note:"",families:[],rows:[],latest:null});expect(page.recovery).toBeNull();});
it("quick ignores a deferred old family list before creating the new account controller",async()=>{const api=await setup();let finish:((value:unknown)=>void)|undefined;let started:()=>void=()=>{};const waiting=new Promise<void>(resolve=>{started=resolve;});vi.mocked((await import("../services/family-api")).listFamilies).mockImplementation((()=>{started();return new Promise<unknown>(resolve=>{finish=resolve;});}) as typeof import("../services/family-api").listFamilies);await import("./home/index");page.setData({today:"2026-09-14",quickTitle:"旧私密",families:[{name:"旧家庭"}]});const loading=invoke("openQuick");await waiting;api.bindRecovery("test",randomUUID());finish?.({items:[{id:randomUUID(),name:"旧账号返回家庭"}],last:{}});await loading;expect(page.data).toMatchObject({quickTitle:"",families:[],quickRows:[],status:"error"});expect(page.quickRecovery).toBeNull();expect([...storage.keys()].filter(k=>k.includes(":input:"))).toEqual([]);});
it.each(["familyChange","loadLatest","keepDraft"])("editor %s discards deferred account-private read continuations",async method=>{const api=await setup();await import("./editor/index");await invoke("load");const familyId=randomUUID();let finish:((value:unknown)=>void)|undefined;const pending=new Promise<unknown>(resolve=>{finish=resolve;});vi.mocked(api.read).mockImplementation((()=>pending) as typeof api.read);page.setData({title:"旧账号",families:[{id:familyId,name:"旧家庭"}],latest:{...task,familyId},id});const loading=invoke(method,{detail:{value:"1"}});await Promise.resolve();api.bindRecovery("test",randomUUID());finish?.(method==="loadLatest"?{task,occurrence:null}:{family:{id:familyId,name:"旧家庭"},members:[],virtualMembers:[]});await loading;expect(page.data).toMatchObject({status:"error",title:"",families:[],rows:[],latest:null});});
it("quick roster response cannot restore old names after an account switch",async()=>{const api=await setup();await import("./home/index");page.setData({today:"2026-09-14"});await invoke("openQuick");const familyId=randomUUID();let finish:((value:unknown)=>void)|undefined;vi.mocked(api.read).mockImplementation((()=>new Promise<unknown>(resolve=>{finish=resolve;})) as typeof api.read);page.setData({families:[{id:familyId,name:"旧家庭"}],quickFamilyIndex:1,quickTitle:"旧账号"});const loading=invoke("loadQuickFamily");await Promise.resolve();api.bindRecovery("test",randomUUID());finish?.({family:{id:familyId,name:"旧家庭"},members:[],virtualMembers:[]});await loading;expect(page.data).toMatchObject({quickTitle:"",families:[],quickRows:[],quickSubjectNames:[],status:"error"});});
it("adding an empty time slot as the first edit persists and restores the incomplete schedule",async()=>{const api=await setup();const recurring={...task,schedule:{kind:"daily" as const,startDate:"2026-09-14",endDate:null,times:["08:00"]}};vi.mocked(api.read).mockImplementation((async(action:string)=>action==="task.get"?{task:recurring,occurrence:null}:{nextOccurrences:[],explanation:""}) as typeof api.read);await import("./editor/index");page.setData({id});await invoke("load");expect(page.dirty).toBe(false);await invoke("addTime");expect(page.dirty).toBe(true);expect([...storage.values()]).toContainEqual(expect.objectContaining({input:expect.objectContaining({times:["08:00",""]})}));await invoke("back");expect(wx.showModal).toHaveBeenCalledWith(expect.objectContaining({title:"保留未保存的输入？"}));await invoke("load");expect(page.data.times).toEqual(["08:00",""]);});

async function setupCreateFamilies(){
  const api=await setup();
  const families=[randomUUID(),randomUUID()].map((id,index)=>({id,name:`家庭${index+1}`,ownerName:"我",myMembershipId:randomUUID(),myRole:"owner" as const,version:1}));
  const familyService=await import("../services/family-api");
  const list=vi.mocked(familyService.listFamilies);
  list.mockResolvedValue({items:families,last:{items:families,nextCursor:null,complete:true,asOf:"2026-09-14T00:00:00.000Z"}});
  const read=vi.mocked(api.read).getMockImplementation();
  vi.spyOn(familyService.familyApi,"read").mockImplementation((async(action:string,payload:{id:string})=>action==="family.get"?{family:families.find(f=>f.id===payload.id),members:[],virtualMembers:[]}:read?.(action as "task.get",payload)) as typeof familyService.familyApi.read);
  return {api,families,list};
}
it("quick family preference survives discarded input and family list reordering",async()=>{
  const {families,list}=await setupCreateFamilies();await import("./home/index");page.setData({today:"2026-09-14"});await invoke("openQuick");await invoke("quickFamilyChange",{detail:{value:"2"}});await invoke("discardQuick");
  list.mockResolvedValue({items:[...families].reverse(),last:{items:[],nextCursor:null,complete:true,asOf:"2026-09-14T00:00:00.000Z"}});
  await invoke("openQuick");expect(page.data.quickFamilyIndex).toBe(1);expect(page.quickRoster).toMatchObject({family:{id:families[1]?.id}});
  await invoke("quickFamilyChange",{detail:{value:"0"}});await invoke("discardQuick");page.setData({familyIndex:2});await invoke("openQuick");expect(page.data.quickFamilyIndex).toBe(1);
});
it("new editor uses quick selection and shares its own selection back to quick add",async()=>{
  const {families}=await setupCreateFamilies();await import("./home/index");page.setData({today:"2026-09-14"});await invoke("openQuick");await invoke("quickFamilyChange",{detail:{value:"2"}});await invoke("discardQuick");const home=page;
  await import("./editor/index");await invoke("load");expect(page.roster).toMatchObject({family:{id:families[1]?.id}});await invoke("familyChange",{detail:{value:"1"}});await invoke("discardInput");
  page=home;await invoke("openQuick");expect(page.data.quickFamilyIndex).toBe(1);
});
it("legacy new drafts select a family while existing personal tasks await explicit migration",async()=>{
  const {families}=await setupCreateFamilies();const {rememberCreateFamily}=await import("../services/create-family");const {captureRecoveryIdentity}=await import("../services/input-recovery");rememberCreateFamily(captureRecoveryIdentity(),families[0]?.id??null);
  await seed();await import("./editor/index");await invoke("load");expect(page.data.familyIndex).toBe(1);await invoke("discardInput");page.setData({id});await invoke("load");expect(page.data.familyIndex).toBe(0);
});
it("inaccessible default requires a family and preferences are isolated by account and environment",async()=>{
  const {api,families,list}=await setupCreateFamilies();const {rememberCreateFamily,readCreateFamily}=await import("../services/create-family");const {captureRecoveryIdentity}=await import("../services/input-recovery");const identity=captureRecoveryIdentity();rememberCreateFamily(identity,families[0]?.id??null);
  list.mockResolvedValue({items:[],last:{items:[],nextCursor:null,complete:true,asOf:"2026-09-14T00:00:00.000Z"}});await import("./editor/index");await invoke("load");expect(page.data).toMatchObject({status:"needsFamily",familyIndex:0});
  api.bindRecovery("test",randomUUID());expect(readCreateFamily(captureRecoveryIdentity(),families)).toBeUndefined();rememberCreateFamily(identity,null);
  api.bindRecovery("other",user);expect(readCreateFamily(captureRecoveryIdentity(),families)).toBeUndefined();api.bindRecovery("test",user);expect(readCreateFamily(captureRecoveryIdentity(),families)).toBe(families[0]?.id);
});

it("without a family both entry points guide joining and cannot submit",async()=>{
  const api=await setup();
  vi.mocked((await import("../services/family-api")).listFamilies).mockResolvedValue({items:[],last:{items:[],complete:true,nextCursor:null,asOf:"2026-09-14T00:00:00.000Z"}});
  const write=vi.spyOn(api,"write");
  await import("./home/index");page.setData({today:"2026-09-14"});await invoke("openQuick");
  expect(wx.switchTab).toHaveBeenCalledWith({url:"/pages/families/index"});expect(page.data.sheet).toBe("");
  page.setData({quickTitle:"不能保存"});await invoke("saveQuick",{currentTarget:{dataset:{}}});expect(write).not.toHaveBeenCalled();
  await import("./editor/index");await invoke("load");expect(page.data.status).toBe("needsFamily");
  page.setData({title:"不能保存"});await invoke("save");expect(write).not.toHaveBeenCalled();
});
it("old personal preference falls back to an active family and never exposes personal creation",async()=>{
  const {families}=await setupCreateFamilies();
  const {captureRecoveryIdentity}=await import("../services/input-recovery");
  const {rememberCreateFamily}=await import("../services/create-family");rememberCreateFamily(captureRecoveryIdentity(),null);
  await import("./editor/index");await invoke("load");expect(page.data.familyIndex).toBe(1);expect(page.data.familyOptions).not.toContain("个人事项");
  const write=vi.spyOn((await import("../services/personal-api")).personalApi,"write").mockResolvedValue({task});
  await invoke("titleInput",{detail:{value:"家庭事项"}});await invoke("save");
  expect(write).toHaveBeenCalledWith("task.create",expect.objectContaining({draft:expect.objectContaining({familyId:families[0]?.id})}),expect.anything());
});

it("quick add resolves the home family by ID when the refreshed list reorders",async()=>{
  const {families,list}=await setupCreateFamilies();await import("./home/index");
  page.setData({today:"2026-09-14",families,familyIndex:1});
  list.mockResolvedValue({items:[...families].reverse(),last:{items:[],complete:true,nextCursor:null,asOf:"2026-09-14T00:00:00.000Z"}});
  await invoke("openQuick");expect(page.quickRoster).toMatchObject({family:{id:families[0]?.id}});expect(page.data.quickFamilyIndex).toBe(2);
});
