'use strict';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages = [
 ['home','首页','跨家庭日常','日期和家庭筛选只影响清单，到时提醒始终汇总所有家庭。'],
 ['detail','事项详情','本次与周期','执行对象与真实记录人分开；完成这次，不会停止后续安排。'],
 ['editor','事项编辑','渐进填写','先记内容，再安排时间与家人。只有查看权限不会自动获得代记或提醒。'],
 ['families','家庭','多个家庭','资料与家庭称呼独立。家庭卡片说明角色，不展示跨家庭的其他私密信息。'],
 ['family','家庭详情','成员与管理','仍属于家庭页面内部视图。常用成员操作靠前，退出与转交独立确认。'],
 ['invitation','邀请家人','发出与接收','邀请可转发，持有者可主动加入。这里只模拟预览和接受，不发送微信消息。'],
 ['progress','家人进度','只看可见记录','不做排名。跳过单列、不计入分母；没有记录，不代表没有完成。'],
 ['recycle','回收站','恢复与保留','只列当前可管理的事项。周期恢复为暂停，历史与有效权限保留。']
];
let noFamily=false;
let page='home', mode='ready', date='今天', family='全部家庭', showDone=false, batch=false, selected=new Set(), current=1, sheetReturn=null;
let me='小雨', familyName='我的小家', activeFamily='我的小家', invited=false, joined=false, revoked=false, recipient=false, series='进行中', reminder=true;
let people=['妈妈','爸爸','小宝','奶奶'];
let draft=null; let preferredFamily=null;
let tasks=[
 {id:1,title:'读 20 分钟绘本',who:'小宝',family:'我的小家',time:'18:00',date:'今天',group:'帮家人',done:false,repeat:true,can:true,manage:true,viewers:['妈妈','奶奶']},
 {id:2,title:'取回干洗的外套',who:'我',family:'我的小家',time:'18:00',date:'今天',group:'我来做',done:false,repeat:false,can:true,manage:true,viewers:[]},
 {id:3,title:'晚饭后散步',who:'爸爸',family:'爸妈家',time:'18:00',date:'今天',group:'关心一下',done:false,repeat:true,can:false,manage:false,viewers:['我']},
 {id:4,title:'给阳台的花浇水',who:'我',family:'我的小家',time:'',date:'今天',group:'我来做',done:true,repeat:false,can:true,manage:true,viewers:[]},
 {id:5,title:'带上体检报告',who:'我',family:'爸妈家',time:'09:00',date:'明天',group:'我来做',done:false,repeat:false,can:true,manage:true,viewers:[]},
 {id:6,title:'整理上个月的照片',who:'我',family:'我的小家',time:'',date:'未安排',group:'我来做',done:false,repeat:false,can:true,manage:true,viewers:[]},
 {id:7,title:'归还图书馆的书',who:'我',family:'我的小家',time:'',date:'已超时',group:'我来做',done:false,repeat:false,can:true,manage:true,viewers:[]}
];
let recycled=[{id:8,title:'整理书桌',who:'小宝',family:'我的小家',time:'20:00',date:'今天',group:'帮家人',done:false,repeat:true,can:true,manage:true,viewers:['妈妈']}];
const button=(label,action,cls='text',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const tag=(s,c='')=>`<span class="tag ${c}">${s}</span>`;
const avatar=(s,c='')=>`<span class="avatar ${c}">${esc(s[0])}</span>`;
const options=(arr,value)=>arr.map(s=>`<option ${s===value?'selected':''}>${esc(s)}</option>`).join('');
const field=(label,id,value='',type='text')=>`<label class="field" for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${draft?.locked&&['edit-date','edit-end'].includes(id)?'disabled':''}>`;
const task=()=>tasks.find(t=>t.id===current)||tasks[0];
const visible=()=>tasks.filter(t=>(family==='全部家庭'||t.family===family)&&t.date===date&&(date!=='已超时'||(!t.done&&!t.skipped)));
function toast(s){$('#toast').textContent=s;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').textContent='',3000)}
function closeSheet(){ $('#overlay').innerHTML=''; if(sheetReturn?.isConnected)sheetReturn.focus(); }
function sheet(title,body){sheetReturn=document.activeElement;$('#overlay').innerHTML=`<div class="overlay"><section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header class="sheet-header"><h3>${title}</h3>${button('×','close','','aria-label="关闭弹层"')}</header><div class="sheet-body">${body}</div></section></div>`;$('#overlay button')?.focus();}
function confirm(title,copy,action,label='确认'){sheet(title,`<div class="notice warning">${copy}</div><div class="actions">${button('取消','close','secondary')}${button(label,action,'primary')}</div>`)}
function go(p){closeSheet();page=p;mode='ready';$('#state').value=mode;render();$('#screen').scrollTop=0;}
function empty(title,copy,action='quick',label='记一件事'){return `<div class="empty"><div class="empty-icon">○</div><h3>${title}</h3><p class="note">${copy}</p>${button(label,action,'secondary')}</div>`}
function noFamilyView(){return `<div class="empty"><div class="empty-icon" aria-hidden="true">家</div><h3>还没有加入家庭</h3><p class="note">创建一个家庭，或加入家人已有的家庭。<br>所有事项都需要归属家庭。</p><div class="actions">${button('创建家庭','create-family','primary')}${button('加入家庭','receive','secondary')}</div></div>`;}
function special(){if(noFamily&&page!=='invitation')return noFamilyView();if(mode==='loading')return '<div class="note">正在加载，请稍候…</div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';
 if(mode==='error')return empty('内容暂时没有加载出来','请检查网络后重试，原有安排仍然保留。','retry','重新加载');
 if(mode==='empty'&&page==='families')return noFamilyView();

 if(mode==='empty'){const e={home:[date==='已超时'?'没有超时未完成事项':'这一天，还没有安排','只填标题，也能记下一件事。','quick','记一件事'],families:['还没有加入家庭','所有事项都需要归属家庭。','create-family','创建家庭'],family:['还没有其他家人','邀请真实家人，或添加无账号成员。','invite','邀请家人'],progress:['暂无共享给你的这一天安排','试着换个日期。没有记录，不代表没有完成。','retry','返回进度'],recycle:['暂时没有删除的事项','删除的事项会保留记录，可在这里恢复。','nav:home','返回首页'],invitation:['这个邀请暂时不可用','请检查口令或请家人重新邀请。','receive','输入邀请口令'],detail:['当前没有可显示的次数','可以按日期查看历史安排。','history','查看历史'],editor:['开始一份新安排','选择家庭，再记下要做的事。','retry','开始填写']}[page];return empty(...e)}return ''}
function stateBanner(){if(mode==='partial')return `<div class="notice warning">${page==='progress'?'进度暂未完整加载，暂不显示统计。':'部分内容未能加载，暂不显示完整总数。'}${button('重新加载','retry')}</div>`;if(mode==='uncertain')return `<div class="notice warning"><b>暂未确认操作结果</b><br>保留原操作内容，请主动重试确认。${button('重试确认结果','resolve')}</div>`;if(mode==='conflict')return `<div class="notice warning">家人已修改这份安排，你的输入已保留。${button('比较最新内容','conflict')}</div>`;if(mode==='readonly')return '<div class="notice">你可以查看这件事和完成记录，暂不能代记或编辑。</div>';return ''}
function taskRow(t){const readonly=!t.can||mode==='readonly';const control=batch?button(`<span>${selected.has(t.id)?'✓':''}</span>`,'select:'+t.id,'check',!t.manage?'disabled aria-label="无管理权限，无法多选"':'aria-label="选择 '+esc(t.title)+'"'):readonly?'<span class="view-symbol" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></svg></span>':button(`<span>${t.done?'✓':''}</span>`,'toggle:'+t.id,'check '+(t.done?'done':''),'aria-label="'+(t.done?'撤销完成':'记录完成')+' '+esc(t.title)+'"');return `<div class="task ${readonly?'task-readonly':'task-actionable'}">${control}<button class="task-copy" data-action="task:${t.id}" ${readonly?'aria-label="仅查看：'+esc(t.title)+'"':''}><strong>${esc(t.title)}</strong><small>${esc(t.who)} · ${esc(t.family)} ${t.repeat?' · 每天':''}</small><small>${t.date==='已超时'?'9 月 14 日 · ':''}${esc(t.time||'不限定时刻')} ${!t.done&&!t.skipped&&(t.time==='18:00'||t.date==='已超时')?tag(t.date==='已超时'?'◷ 计划日期已过':'◷ 已到计划时间','warn'):''}${t.done?tag('已完成','green'):t.skipped?tag('已跳过','gray'):''}</small></button><span class="arrow" aria-hidden="true"><span class="nav-chevron" aria-hidden="true"></span></span></div>`}

function home(){const list=visible();return `<div class="hero"><div><p>9 月 15 日 · 星期二</p><h2>今天的事，慢慢来。</h2></div><span class="hero-mark">家</span></div><button class="reminder" data-action="reminders"><span class="bell">◷</span><span><strong>${tasks.filter(t=>t.time==='18:00'&&!t.done&&!t.skipped&&!t.dismissed).length} 件事到了提醒时间</strong><small>汇总所有家庭中提醒你的事项</small></span><span class="push"><span class="nav-chevron" aria-hidden="true"></span></span></button><div class="toolbar"><select id="home-family" aria-label="筛选家庭">${options(['全部家庭',familyName,'爸妈家'],family)}</select>${button(batch?'取消多选':'多选','batch-toggle')}</div><div class="dates">${['今天','明天','未安排','已超时','日期'].map(d=>button(d,'date:'+d,date===d?'active':'')).join('')}</div>${stateBanner()}${mode==='partial'?'':`<div class="summary"><span>${date==='已超时'?`未完成 ${list.filter(t=>!t.done&&!t.skipped).length} 件`:`已完成 ${list.filter(t=>t.done).length} / ${list.filter(t=>!t.skipped).length} 件 · 跳过 ${list.filter(t=>t.skipped).length}`}</span>${date==='已超时'?'':button(showDone?'隐藏已完成':'显示已完成','show-done')}</div>`}${['我来做','帮家人','关心一下'].map(g=>{const a=list.filter(t=>(mode==='readonly'?'关心一下':!t.can?'关心一下':t.group)===g&&(showDone||!t.done));return a.length?`<h4 class="section-label ${g==='关心一下'?'view-section':''}">${g==='关心一下'?'关心家人':g} · ${a.length}</h4><div class="list">${a.map(taskRow).join('')}</div>`:''}).join('')}${!list.filter(t=>showDone||!t.done).length?empty(list.length?'这一页的事情都完成了':'这里还没有安排',list.length?'可以打开已完成，回看这一天。':'从一件小事开始。'):''}<p class="note" style="text-align:center">一家人的小事，一件一件来。</p>`}
function detail(){const t=task();return `<div class="small">${esc(t.family)} / ${esc(t.who)} ${t.who==='小宝'?tag('无账号成员'):''}</div><h2 class="detail-title">${esc(t.title)}</h2><div class="note">9 月 15 日 · ${t.time||'不限定时刻'} ${t.repeat?'　↻ 每天':''}</div>${stateBanner()}<div class="card detail-status"><div class="row between"><h3>这一次</h3>${tag(t.done?'已完成':t.skipped?'已跳过':'待完成',t.done?'green':'')}</div><p class="note">${t.done?`${esc(t.who)}已完成 · 由我记录<br>实际完成 ${esc(t.actual||'18:30')} · 记录时间 18:30`:t.skipped?'已跳过这次，不计入完成分母。':'还没有完成记录。'}</p>${!t.done&&!t.skipped&&t.can&&mode!=='readonly'?button('补记时间 / 跳过这次','record','secondary'):''}</div><div class="card"><h4>这件事的安排</h4><div class="cell"><span>执行对象</span><span>${esc(t.who)}</span></div><div class="cell"><span>谁可以看</span><span>${esc(t.viewers.join('、')||'仅自己')}</span></div><div class="cell"><span>我的小程序内提醒</span><span>${reminder?'已开启':'已关闭'}</span></div><p class="note">${t.who==='小宝'?'由家庭拥有人妈妈管理，小宝的记录仍展示为小宝。':'查看、代记和管理权限分别设置。'}</p>${button('查看与提醒设置','settings','secondary full')}</div><div class="card"><h4>本次记录</h4><div class="timeline"><p>${t.done?`18:30　我记录了${esc(t.who)}的完成`:'尚未记录完成'}<br><small>实际完成时间与记录时间分别保留</small></p></div></div>${t.repeat?`<div class="card"><div class="row between"><h4>整个周期</h4>${tag(series)}</div><p class="note">每天 · ${t.time||'不限定时刻'}<br>修改只影响未来安排，历史执行对象保留。</p>${button('按日期查看历史次数','history','secondary full')}${t.manage&&mode!=='readonly'?`<div class="actions">${series==='进行中'?button('暂停','pause','secondary'):series==='已暂停'?button('继续','resume','secondary'):''}${series!=='已停止'?button('停止后续','stop','secondary'):''}</div>`:''}</div>`:''}`}
function freshDraft(){return {title:'',note:'',family:familyName,who:'自己',repeat:'不重复',date:'2026-09-16',end:'',times:[],week:['二','四'],view:false,help:false,remind:false}}
function editor(){draft ||= {...freshDraft(),title:'读 20 分钟绘本',family:'我的小家',who:'小宝',repeat:'每天',times:['19:30']};return `${stateBanner()}<div class="card"><label class="field" for="edit-title">要记什么事</label><input id="edit-title" class="input-title" value="${esc(draft.title)}" maxlength="100" placeholder="例如：读 20 分钟绘本"><label class="field" for="edit-note">备注（可选）</label><textarea id="edit-note" placeholder="补充需要家人知道的事">${esc(draft.note)}</textarea></div><div class="card"><h4>为谁安排</h4><label class="field" for="edit-family">所属家庭</label><select id="edit-family" ${draft.existing?'disabled':''}>${options([familyName,'爸妈家'],draft.family)}</select><label class="field" for="edit-who">执行对象</label><select id="edit-who" ${draft.locked?'disabled':''}>${options(draft.family==='爸妈家'?['自己','爸爸','妈妈']:['自己',...people],draft.who)}</select><p class="notice">${draft.who==='小宝'?'小宝没有独立账号。事项由拥有人妈妈管理，妈妈和创建人可见。':draft.who==='自己'?'默认仅自己可见。共享给家人需要明确选择。':`${esc(draft.who)}将能查看并记录完成，无需接受；不会自动开启提醒。`}</p></div><div class="card"><h4>什么时候做</h4>${draft.locked?'<p class="notice">已完成或已跳过的一次性事项保留原安排。需调整时另建，或先撤销跳过。</p>':''}<div class="chips">${['不重复','每天','每周'].map(r=>button(r,'repeat:'+r,draft.repeat===r?'active':'',draft.locked||draft.existing&&task().repeat&&r==='不重复'?'disabled':'')).join('')}</div>${field(draft.repeat==='不重复'?'计划日期（可不填）':'开始日期','edit-date',draft.date,'date')}${draft.repeat!=='不重复'?`${field('结束日期（可选）','edit-end',draft.end,'date')}${draft.repeat==='每周'?`<label class="field">每周哪几天</label><div class="chips">${['一','二','三','四','五','六','日'].map(w=>button(w,'weekday:'+w,draft.week.includes(w)?'active':'','aria-pressed="'+draft.week.includes(w)+'"')).join('')}</div>`:''}`:''}<label class="field">具体时刻（可选）</label>${draft.times.map((t,i)=>`<div class="row"><input type="time" data-time="${i}" aria-label="第 ${i+1} 个时刻" value="${t}">${button('×','remove-time:'+i,'','aria-label="删除时刻"')}</div>`).join('')}${button('＋ 添加时刻'+(draft.repeat==='不重复'?'':' · 最多 6 个'),'add-time','text',draft.times.length>=(draft.repeat==='不重复'?1:6)||draft.locked?'disabled':'')}<p class="note">不填时刻即当天安排，不产生午夜提醒。${draft.repeat!=='不重复'?'更换执行对象或修改周期，仅影响未来安排。':''}</p>${draft.repeat!=='不重复'?button('查看接下来 3 次安排','preview','secondary full'):''}</div><div class="card"><div class="row between"><h4>谁一起照应</h4>${button('设置家人权限','permissions')}</div><p class="note">${draft.view?'奶奶可查看'+(draft.help?'、代记':'')+(draft.remind?'、接收提醒':''):'未添加其他可见家人'}</p><label class="choice"><input type="checkbox" id="my-reminder" ${reminder?'checked':''}>提醒我 · 小程序内</label><p class="note">${reminder?(draft.times.length?'按具体时刻显示到时提示':'已开启 · 待设置时刻'):'我的提醒未开启'}。关闭小程序后不会发送通知。</p></div><p id="editor-error" class="error-text"></p>`}
function families(){return `<button class="profile" data-action="profile">${avatar(me)}<div><h2>${esc(me)}</h2><small>查看与编辑个人资料</small></div><span class="push"><span class="nav-chevron" aria-hidden="true"></span></span></button>${stateBanner()}<div class="row between"><h3>我的家庭</h3><small>2 个家庭</small></div>${[familyName,'爸妈家'].map((f,i)=>`<button class="family-card ${i===0?'cover':''}" data-action="family:${esc(f)}"><div class="family-heading"><h3>${esc(f)}</h3><span aria-hidden="true"><span class="nav-chevron" aria-hidden="true"></span></span></div><div class="family-meta"><span>${i===0?people.length:3} 位成员</span><span class="family-role">${i===0?'你是家庭拥有人':'你是家庭成员'}</span></div></button>`).join('')}<div class="actions">${button('＋ 创建家庭','create-family','secondary')}${button('加入家庭','receive','secondary')}</div><div class="card">${button('<span>家人进度</span><span>看看家人的安排 <span class="nav-chevron" aria-hidden="true"></span></span>','nav:progress','cell')}${button('<span>回收站</span><span>找回删除的事项 <span class="nav-chevron" aria-hidden="true"></span></span>','nav:recycle','cell')}</div><p class="note">家庭内的称呼独立设置，个人资料只保存在本机。</p>`}
function memberSummary(p){const list=tasks.filter(t=>t.family===activeFamily&&t.who===(p==='妈妈'&&activeFamily!=='爸妈家'?'我':p)&&t.date==='今天');return list.length?`已完成 ${list.filter(t=>t.done).length} / ${list.filter(t=>!t.skipped).length} 件 · 跳过 ${list.filter(t=>t.skipped).length}`:'今日暂无共享给你的安排'}
function familyPage(){const owner=activeFamily!=='爸妈家';const roster=owner?people:['爸爸','妈妈','我'];return `<div class="card cover"><h2>${esc(activeFamily)}</h2><p class="note">拥有人 · ${activeFamily==='爸妈家'?'爸爸':'妈妈（我）'}</p>${owner?button('修改家庭名称','rename-family','secondary'):''}</div>${stateBanner()}<div class="row between"><h3>家人</h3><small>${roster.length} 位 · 今日可见进度</small></div><div class="card">${roster.map((p,i)=>`<div class="member-line"><div class="row">${avatar(p,i%2?'mint':'')}<div><strong>${esc(p)} ${p==='小宝'?tag('无账号'):''}</strong><small>${i===0?'家庭拥有人':p==='小宝'?'由拥有人管理':'真实成员'}</small></div>${owner?button('管理','member:'+i,'text push'):''}</div><p class="note" style="margin:10px 0 0 50px">${mode==='partial'?'今日进度暂未加载':memberSummary(p)}</p></div>`).join('')}</div>${owner?`<div class="actions">${button('邀请家人','invite','secondary')}${button('添加无账号成员','add-member','secondary')}</div>`:''}<div class="card">${owner?button('<span>转交家庭拥有权</span><span>先查看影响 <span class="nav-chevron" aria-hidden="true"></span></span>','transfer','cell'):''}${button('<span>退出这个家庭</span><span>先交接事项 <span class="nav-chevron" aria-hidden="true"></span></span>','exit','cell')}${button('<span>回收站</span><span>恢复事项 <span class="nav-chevron" aria-hidden="true"></span></span>','nav:recycle','cell')}</div>`}
function invitation(){return `${stateBanner()}<div class="chips">${button('发出邀请','send-view',!recipient?'active':'')}${button('接收邀请','receive-view',recipient?'active':'')}</div>${recipient?joined?`<div class="card cover"><h2>你已加入这个家庭</h2><p class="note">重复接受不会再次添加成员。</p>${button('查看家人','nav:family','primary')}</div>`:`<div class="card"><h3>加入家人的日常</h3>${field('邀请口令','invite-token','','text')}${button('预览邀请','invite-preview','secondary full')}<p class="note">从有效分享卡片进入时，直接展示家庭预览。</p></div>`:`<div class="card cover"><div class="portraits row">${people.slice(0,3).map((p,i)=>avatar(p,i?'mint':'')).join('')}</div><h2>邀请家人，<br>一起照应日常。</h2><p class="note">${esc(activeFamily)} · 拥有人妈妈</p><div class="notice">邀请有效期 7 天，可转发供多人使用。持有有效邀请的人确认后即可加入。</div>${button(invited?'生成另一份邀请':'生成新邀请','generate','primary')}</div>${invited?`<div class="card"><div class="row between"><h4>${revoked?'已撤销':'邀请已生成'}</h4>${tag(revoked?'不可加入':'有效')}</div><p class="note">有效至 2026 年 9 月 22 日 18:30</p>${!revoked?`${button('分享给微信好友','share-invite','primary')}${button('复制邀请口令','copy-invite','secondary full')}${button('撤销这份邀请','revoke','text full')}`:''}</div>`:''}`}`}
function progress(){const list=tasks.filter(t=>t.family===activeFamily&&t.date==='今天'), names=[...new Set(list.map(t=>t.who))];return `<div class="hero"><div><p>各自忙碌，也彼此照应</p><h2>家人的这一天</h2></div><span class="hero-mark">伴</span></div><select id="progress-family" aria-label="查看家庭">${options([familyName,'爸妈家'],activeFamily)}</select><div class="toolbar"><input type="date" id="progress-date" aria-label="查看日期" value="2026-09-15"><select id="progress-person" aria-label="执行对象">${options(['全部家人',...names],'全部家人')}</select></div>${stateBanner()}${mode==='partial'?'':names.map(n=>{const a=list.filter(t=>t.who===n),done=a.filter(t=>t.done).length,skipped=a.filter(t=>t.skipped).length,total=a.length-skipped;return `<div class="card progress-person" data-person="${esc(n)}"><div class="row">${avatar(n,n==='小宝'?'mint':'')}<div><h3>${esc(n)}</h3><small>${n==='小宝'?'无账号成员':'真实成员'}</small></div><div class="mini-stat push"><b>${done}</b><span>/ ${total} 件</span></div></div><div class="progress-track"><span style="width:${total?done/total*100:0}%"></span></div><p class="note">已完成 ${done} · 待完成 ${total-done} · 已跳过 ${skipped}</p>${a.map(t=>`<div class="cell"><span>${esc(t.title)}</span><span>${t.done?'已完成':t.skipped?'已跳过':'待记录'}</span></div>`).join('')}</div>`}).join('')}<p class="notice">只统计共享给你的安排。<br>没有记录，不代表没有完成。</p>${button('管理家庭','nav:family','secondary full')}`}
function recycle(){return `<p class="note">删除的事项仍可找回，完成历史会一起保留。</p><select id="recycle-family" aria-label="筛选家庭">${options(['全部家庭',familyName,'爸妈家'],'全部家庭')}</select>${stateBanner()}${recycled.length?recycled.map(t=>`<div class="card recycle-item" data-family="${esc(t.family)}"><div class="row between"><h3>${esc(t.title)}</h3>${tag(t.repeat?'周期事项':'一次性','gray')}</div><p class="note">${esc(t.family)} · ${esc(t.who)}<br>9 月 14 日删除</p>${t.repeat?'<div class="notice">恢复后为暂停状态，历史保留，删除期间不补次数。</div>':''}${button('恢复这件事','restore:'+t.id,'secondary full')}</div>`).join(''):empty('暂时没有删除的事项','删除的事项会保留记录，可在这里恢复。','nav:home','返回首页')}`}
function render(){const p=pages.find(p=>p[0]===page);$('#navigation').innerHTML=pages.map((p,i)=>button(`<span>${String(i+1).padStart(2,'0')}</span>${p[1]}<em>${p[2]}</em>`,'nav:'+p[0],page===p[0]?'selected':'')).join('');$('#caption').textContent=p[1];$('#annotation').textContent=p[3];$('#app-title').innerHTML=(['home','families'].includes(page)?'':button('‹','nav:'+(page==='family'?'families':page==='detail'||page==='editor'?'home':'families'),'','aria-label="返回"'))+(page==='home'?'家庭待办':p[1]);$('#screen').innerHTML=special()||({home,detail,editor,families,family:familyPage,invitation,progress,recycle}[page])();let bottom='';if(page==='home'&&!noFamily)bottom=`<div class="bottom-actions">${button(batch?`增加可见人 · ${selected.size} / 20`:'＋ 记一件事',batch?'batch':'quick','primary',batch&&!selected.size?'disabled':'')}</div>`;if(page==='detail'&&!noFamily&&task().can&&mode!=='readonly'&&mode!=='error'&&mode!=='loading')bottom=`<div class="bottom-actions actions">${button('更多','settings','secondary')}${button(task().done||task().skipped?'撤销这次记录':`记录${task().who==='我'?'':esc(task().who)}完成`,'toggle:'+task().id,'primary')}</div><div class="safe"></div>`;if(page==='editor'&&!noFamily&&!['loading','error'].includes(mode))bottom=`<div class="bottom-actions">${button(mode==='uncertain'?'重试确认保存':'保存这份安排',mode==='uncertain'?'resolve':'save-editor','primary',['conflict','readonly'].includes(mode)?'disabled':'')}</div><div class="safe"></div>`;if(['home','families','family'].includes(page))bottom+=`<div class="tabbar">${button('<b>⌂</b>首页','nav:home',page==='home'?'active':'')}${button('<b>♧</b>家庭','nav:families',page!=='home'?'active':'')}</div>`;$('#bottom').innerHTML=bottom;}
function permissions(){sheet('谁一起照应',`<p class="note">先允许查看，再单独设置代记和提醒。</p><div class="card"><h4>${esc(draft.who==='小宝'?'妈妈 · 必要可见人':draft.who+' · 执行对象')}</h4><p class="note">${draft.who==='小宝'?'家庭拥有人管理小宝的事项':'执行对象有必要查看和本人记录权限'}，不能取消必要可见。</p><div class="permission"><label class="choice"><input id="permission-view" type="checkbox" ${draft.view?'checked':''}>奶奶可以查看</label><div class="subchoices"><label class="choice"><input id="permission-help" type="checkbox" ${draft.help?'checked':''} ${!draft.view?'disabled':''}>允许代记完成</label><label class="choice"><input id="permission-remind" type="checkbox" ${draft.remind?'checked':''} ${!draft.view?'disabled':''}>接收小程序内提醒</label></div></div><div class="permission"><h4>爸爸</h4><p class="note">已自行关闭提醒，需本人开启。<br>管理者无法替他重新开启。</p></div></div>${button('保留设置','close','primary')}`)}
function captureDraft(){if(!$('#edit-title'))return;Object.assign(draft,{title:$('#edit-title').value,note:$('#edit-note').value,family:$('#edit-family').value,who:$('#edit-who').value,date:$('#edit-date').value,end:$('#edit-end')?.value||'',times:[...document.querySelectorAll('[data-time]')].map(e=>e.value)})}
function action(a){const [name,...parts]=a.split(':'),v=parts.join(':');
 if(name==='nav'){if(page==='editor'){captureDraft();confirm('保留未保存的输入？','返回后可以继续填写；不会自动提交。','leave:'+v,'保留并返回');return}go(v);return}
 if(name==='leave'){go(v);return}if(name==='close'){if($('#quick-title')?.value){confirm('保留未保存的输入？','这份输入只用于本地演示。','keep-quick','保留草稿');return}closeSheet();return}
 if(name==='retry'||name==='resolve'){mode='ready';$('#state').value=mode;render();toast(name==='resolve'?'演示：已确认原操作结果':'内容已重新加载');return}
 if(name==='date'){date=v;if(v==='日期'){sheet('选择日期',`${field('查看哪一天','calendar','2026-09-16','date')}${button('查看这一天','calendar-apply','primary')}`)}else render();return}
 if(name==='calendar-apply'){const d=$('#calendar').value;date=d==='2026-09-15'?'今天':d==='2026-09-16'?'明天':d;closeSheet();render();return}
 if(name==='show-done'){showDone=!showDone;render();return}
 if(name==='task'){current=Number(v);go('detail');return}
 if(name==='toggle'){const t=tasks.find(t=>t.id===Number(v));if(!t?.can||mode==='readonly')return;if(mode==='uncertain'){toast('请先确认未决操作的结果');return}t.done=t.skipped?false:!t.done;t.skipped=false;render();toast(t.done?`${t.who}已完成 · 由我记录`:'已撤销本次记录');return}
 if(name==='batch-toggle'){batch=!batch;selected.clear();render();return}
 if(name==='select'){const t=tasks.find(t=>t.id===Number(v));if(!t?.manage)return;selected.has(t.id)?selected.delete(t.id):selected.size<20?selected.add(t.id):toast('一次最多选择 20 个不同事项');render();return}
 if(name==='quick'){sheet('记一件事',`<label class="field" for="quick-title">要记什么事</label><input id="quick-title" placeholder="例如：明天取快递" value="${esc(action.quickDraft||'')}" maxlength="100"><label class="field" for="quick-date">计划日期</label><select id="quick-date">${options(['今天','明天','未安排'],'明天')}</select><label class="field" for="quick-family">所属家庭</label><select id="quick-family">${options([familyName,'爸妈家'],preferredFamily||(family==='全部家庭'?familyName:family))}</select><p class="notice">执行对象为自己，仅自己可见。提醒我默认开启；未设置具体时刻时不产生到时提示。</p><p id="quick-error" class="error-text"></p>${button('更多安排 · 周期与家人','full-editor','secondary full')}${button('保存，再记一件','save-quick','primary')}`);return}
 if(name==='keep-quick'){closeSheet();toast('演示草稿已保留');return}
 if(name==='save-quick'){const title=$('#quick-title').value.trim();if(!title){$('#quick-error').textContent='先写下要记的事。';$('#quick-title').focus();return}preferredFamily=$('#quick-family').value;tasks.push({id:Date.now(),title,who:'我',family:$('#quick-family').value,date:$('#quick-date').value,time:'',group:'我来做',done:false,repeat:false,can:true,manage:true,viewers:[]});action.quickDraft='';$('#quick-title').value='';$('#quick-error').textContent='已保存，可以接着记下一件。';$('#quick-title').focus();render();return}
 if(name==='full-editor'){draft={...freshDraft(),title:$('#quick-title').value,family:$('#quick-family').value,date:$('#quick-date').value==='未安排'?'':$('#quick-date').value==='今天'?'2026-09-15':'2026-09-16'};go('editor');return}
 if(name==='reminders'){sheet('到时提醒',`<p class="notice">汇总所有家庭。只在使用小程序时提示，关闭后不会发送微信通知。</p>${tasks.filter(t=>t.time==='18:00'&&!t.done&&!t.skipped).map(t=>`<div class="card"><h4>${esc(t.title)}</h4><p class="note">${esc(t.family)} · ${esc(t.who)} · 18:00 ${t.dismissed?'· 已收起':''} ${t.read?'· 已读':''}</p><div class="actions">${button('查看','reminder-read:'+t.id,'secondary')}${button(t.dismissed?'已收起':'收起提示','dismiss:'+t.id,'text',t.dismissed?'disabled':'')}</div></div>`).join('')||'<p class="note">暂时没有待处理的到时提醒。</p>'}<p class="note">演示中保留已收起记录。收起提示不会完成事项。</p>`);return}
 if(name==='dismiss'){tasks.find(t=>t.id===Number(v)).dismissed=true;action('reminders');render();return}if(name==='reminder-read'){const t=tasks.find(t=>t.id===Number(v));t.read=true;current=t.id;go('detail');return}
 if(name==='settings'){const t=task();sheet('事项设置',`<p class="note">${esc(t.title)} · ${esc(t.family)}</p>${t.manage&&mode!=='readonly'?button('编辑这份安排','edit-current','secondary full'):''}${button(reminder?'关闭我的提醒':'开启我的提醒','reminder-toggle','secondary full')}${t.manage&&mode!=='readonly'?`${button('共享这件事','edit-access','secondary full')}${button('删除整个事项','delete','danger-button full')}`:''}${button('回收站','nav:recycle','text full')}`);return}
 if(name==='reminder-toggle'){reminder=!reminder;closeSheet();render();toast(reminder?'已开启我的提醒':'已关闭我的提醒');return}
 if(name==='edit-current'||name==='edit-access'){const t=task();draft={...freshDraft(),title:t.title,family:t.family,who:t.who==='我'?'自己':t.who,repeat:t.repeat?'每天':'不重复',times:t.time?[t.time]:[],existing:true,locked:!t.repeat&&(t.done||t.skipped)};go('editor');if(name==='edit-access')permissions();return}
 if(name==='repeat'){captureDraft();draft.repeat=v;draft.times=draft.times.slice(0,v==='不重复'?1:6);render();return}if(name==='weekday'){captureDraft();draft.week.includes(v)?draft.week=draft.week.filter(x=>x!==v):draft.week.push(v);render();return}
 if(name==='add-time'){captureDraft();draft.times.push('19:30');render();return}if(name==='remove-time'){captureDraft();draft.times.splice(Number(v),1);render();return}
 if(name==='permissions'){captureDraft();permissions();return}
 if(name==='preview'){captureDraft();const days=[];const base=new Date(draft.date+'T00:00:00Z');if(!draft.date||Number.isNaN(base.getTime())){toast('请先选择有效开始日期');return}for(let i=0;i<60&&days.length<3;i++){const d=new Date(base);d.setUTCDate(d.getUTCDate()+i);const str=d.toISOString().slice(0,10);if(draft.end&&str>draft.end)break;if(draft.repeat==='每周'&&!draft.week.includes(['日','一','二','三','四','五','六'][d.getUTCDay()]))continue;for(const time of draft.times.length?[...new Set(draft.times)].sort():['不限定时刻']){if(str<'2026-09-15'||str==='2026-09-15'&&time!=='不限定时刻'&&time<='18:30')continue;days.push(str+' · '+time);if(days.length===3)break}}sheet('接下来的安排',`<p class="notice">正式产品由服务端计算。此处以 9 月 15 日 18:30 为固定演示时间，时区为上海。</p>${days.map(d=>`<div class="card mono">${d} · ${esc(draft.who)}</div>`).join('')||'<p class="note">此范围内没有有效安排，请检查星期与起止日期。</p>'}`);return}
 if(name==='save-editor'){captureDraft();if(!draft.title.trim()){ $('#editor-error').textContent='先写下要记的事。';$('#edit-title').focus();return}if(draft.repeat!=='不重复'&&!draft.date||draft.repeat==='每周'&&!draft.week.length||draft.end&&draft.end<draft.date||draft.times.some(t=>!t)||new Set(draft.times).size!==draft.times.length||draft.times.length&&!draft.date){$('#editor-error').textContent='请检查起止日期、星期和时刻；时刻不能重复。';$('#editor-error').scrollIntoView({block:'center'});return}const data={title:draft.title,who:draft.who==='自己'?'我':draft.who,family:draft.family,time:draft.times[0]||'',date:draft.date==='2026-09-15'?'今天':draft.date==='2026-09-16'?'明天':draft.date||'未安排',repeat:draft.repeat!=='不重复',viewers:draft.view?['奶奶']:[]};if(draft.existing)Object.assign(task(),data);else{current=Date.now();tasks.push({...data,id:current,group:data.who==='我'?'我来做':'帮家人',can:true,manage:true,done:false})}draft=null;go('detail');toast('演示安排已保存');return}
 if(name==='record'){sheet('记录这一次',`${field('实际完成时间','actual-time','2026-09-15T18:30','datetime-local')}${field('记录备注（可选）','record-note')}<p class="note">执行对象：${esc(task().who)} · 记录人：我<br>补记仅用于当前次，系统记录时间另行保留。</p>${button('保存完成记录','save-record','primary')}${button('跳过这次','skip','secondary full')}`);return}
 if(name==='save-record'){const val=$('#actual-time').value;if(!val||val>'2026-09-15T18:30'){toast('实际完成时间不能晚于当前演示时间');return}task().done=true;task().actual=val;task().recordNote=$('#record-note').value;closeSheet();render();return}
 if(name==='skip'){confirm('跳过这一次？','只跳过这一次，保留记录，不计入完成分母，不改变后续计划。','skip-confirm','确认跳过');return}if(name==='skip-confirm'){task().skipped=true;task().done=false;closeSheet();render();return}
 if(name==='history'){sheet('历史次数',`${field('查看日期','history-date','2026-09-14','date')}${button('查看这天','history-show','secondary full')}<div id="history-content" class="card"><h4>9 月 14 日 · 19:30</h4><p class="note">小宝已完成 · 由奶奶记录<br>实际完成 19:45 · 记录时间 19:48<br>当前页为历史样例，正式实现按所选次数独立操作。</p></div>`);return}
 if(name==='history-show'){$('#history-content').innerHTML=`<h4>${esc($('#history-date').value)}</h4><p class="note">此设计样例仅提供 9 月 14 日历史记录；其他日期未模拟。</p>`;return}
 if(['pause','resume','stop','delete'].includes(name)){const map={pause:['暂停整个周期？','此前未完成的次数保留；暂停期间不产生新次数。','确认暂停'],resume:['继续这个周期？','演示下一次：9 月 16 日 19:30。不补暂停期间的次数。','确认继续'],stop:['停止后续安排？','已到时次数与历史保留，停止后不能重新继续。','停止后续'],delete:['删除整个事项？','整个系列及历史暂时从列表、提醒和进度隐藏，可从回收站恢复。','移入回收站']}[name];confirm(map[0],map[1],name+'-confirm',map[2]);return}
 if(['pause-confirm','resume-confirm','stop-confirm'].includes(name)){series=name==='pause-confirm'?'已暂停':name==='resume-confirm'?'进行中':'已停止';closeSheet();render();return}
 if(name==='delete-confirm'){recycled.push({...task(),stopped:series==='已停止'});tasks=tasks.filter(t=>t.id!==current);go('recycle');toast('已移入回收站');return}
 if(name==='restore'){confirm('恢复这件事？','保留历史和当前有效权限。周期恢复后暂停，已停止的周期不能继续；不会恢复已退出成员的访问权。','restore-confirm:'+v,'确认恢复');return}if(name==='restore-confirm'){const t=recycled.find(t=>t.id===Number(v));tasks.push(t);recycled=recycled.filter(x=>x.id!==t.id);series=t.stopped?'已停止':'已暂停';closeSheet();render();toast('已恢复，可在首页找到这件事');return}
 if(name==='family'){activeFamily=v;go('family');return}if(name==='profile'){sheet('个人资料',`<div class="row">${avatar(me)}<p class="note">正式页面使用微信头像选择；<br>此处不申请头像权限。</p></div>${field('昵称','profile-name',me)}<p class="note">资料只保存在本机，家庭内称呼单独维护。</p>${button('保存资料','save-profile','primary')}`);return}if(name==='save-profile'){if(!$('#profile-name').value.trim())return;me=$('#profile-name').value.trim().slice(0,32);closeSheet();render();return}
 if(['create-family','rename-family','add-member'].includes(name)){sheet(name==='create-family'?'创建家庭':name==='rename-family'?'修改家庭名称':'添加无账号成员',`${field(name==='add-member'?'家人的称呼':'家庭名称','family-input',name==='rename-family'?activeFamily:'')}${name==='create-family'?field('我在家里的称呼','my-name','妈妈'):''}${name==='add-member'?'<p class="notice">没有独立账号，相关事项由家庭拥有人管理。不会自行收到提醒。</p>':''}${button(name==='create-family'?'创建家庭':'保存','save-family:'+name,'primary')}`);return}
 if(name==='save-family'){const value=$('#family-input').value.trim();if(!value){toast('请填写名称或称呼');return}if(v==='create-family')noFamily=false;if(v==='add-member')people.push(value.slice(0,12));else {familyName=value.slice(0,24);activeFamily=familyName}go('family');toast('演示数据已更新');return}
 if(name==='member'){const i=Number(v),p=people[i];sheet('管理'+esc(p),`${field('家庭内称呼','member-name',p)}${button('保存称呼','rename-member:'+i,'primary')}${i?button('删除成员','remove-member:'+i,'danger-button full'):'<p class="note">当前拥有人须先转交拥有权，才能退出家庭。</p>'}`);return}if(name==='rename-member'){const n=$('#member-name').value.trim();if(!n)return;people[Number(v)]=n.slice(0,12);closeSheet();render();return}
 if(name==='remove-member'){const p=people[Number(v)];confirm('删除'+esc(p)+'？',p==='小宝'?'删除会停用无账号成员；历史身份和未结束事项保留，由拥有人继续管理。':'该成员的事项与创建管理职责默认交接给拥有人。示例：3 项普通事项，其中 1 项仅本人可见；2 项创建管理职责。历史不变，不影响其其他家庭事项。','remove-confirm:'+v,'确认删除');return}if(name==='remove-confirm'){people.splice(Number(v),1);closeSheet();render();return}
 if(name==='invite'){recipient=false;go('invitation');return}if(name==='receive'){recipient=true;go('invitation');return}if(name==='send-view'||name==='receive-view'){recipient=name==='receive-view';render();return}if(name==='generate'){invited=true;revoked=false;render();return}
 if(name==='share-invite'||name==='copy-invite'){sheet('邀请分享预览',`<div class="card cover"><h3>${esc(activeFamily)}</h3><p class="note">妈妈邀请你一起照应家人的日常</p></div><p class="notice">正式小程序使用微信分享卡片；此处没有发送邀请，也没有真实邀请口令。</p>${button('模拟接收方打开','invite-preview','primary')}`);return}
 if(name==='invite-preview'){if(revoked){sheet('邀请不可用','<p class="notice warning">这份邀请已撤销，请联系家人重新发出邀请。</p>');return}sheet('你收到一份家庭邀请',`<div class="card cover"><h2>${esc(activeFamily)}</h2><p class="note">妈妈邀请你加入 · 7 天内有效</p></div>${field('我在家里的称呼','join-name','奶奶')}<p class="notice">确认后加入家庭。不会自动向你公开其他成员的私密事项。</p>${button('接受邀请并加入','accept','primary')}`);return}if(name==='accept'){if(!$('#join-name').value.trim()){toast('请填写家庭称呼');return}joined=true;noFamily=false;recipient=true;go('invitation');toast('演示：已加入家庭');return}
 if(name==='revoke'){confirm('撤销这份邀请？','撤销后阻止后续加入，已加入的家人仍保留。','revoke-confirm','撤销邀请');return}if(name==='revoke-confirm'){revoked=true;closeSheet();render();return}
 if(name==='transfer'){sheet('转交家庭拥有权',`<label class="field" for="successor">选择承接人</label><select id="successor">${options(people.filter(p=>p!=='妈妈'&&p!=='小宝'),'爸爸')}</select><p class="notice">只能选择有效真实成员。转交后你仍在家庭中，退出需要另行确认。</p>${button('查看交接影响','transfer-preview','primary')}`);return}
 if(name==='transfer-preview'){const to=$('#successor').value;if(!to){toast('请先邀请另一位真实家人');return}confirm('确认转交给'+esc(to)+'？',`示例：2 项无账号成员事项的管理归属交给${esc(to)}，历史执行对象与记录不变。正式提交须使用最新交接预览。`,'transfer-confirm','确认转交');return}
 if(name==='transfer-confirm'){closeSheet();toast('演示交接确认完成；家庭角色变更未模拟');return}
 if(name==='exit'&&activeFamily==='爸妈家'){action('exit-preview');return}if(name==='exit'){sheet('退出这个家庭',`<p class="notice warning">当前你是家庭拥有人，需要先转交给另一位真实成员。没有人可承接时，先邀请家人。</p>${button('转交拥有权','transfer','primary')}${button('查看普通成员退出样例','exit-preview','secondary full')}`);return}
 if(name==='exit-preview'){confirm('退出并交接给妈妈？','示例：3 项普通事项（其中 1 项仅本人可见）、2 项创建管理职责将交给妈妈。只显示数量，不泄露私密事项标题。退出后失去该家庭访问权，历史保留，其他家庭不受影响。','exit-confirm','确认退出并交接');return}
 if(name==='exit-confirm'){go('families');toast('演示交接确认完成；实际成员关系未改变');return}
 if(name==='batch'){const groups=[...new Set(tasks.filter(t=>selected.has(t.id)).map(t=>t.family))];sheet('批量增加可见人',`<p class="notice">保留原名单，不自动增加代记或提醒。各项保留原所属家庭。</p>${groups.map((g,i)=>`<div class="card"><h4>${esc(g)} · ${tasks.filter(t=>selected.has(t.id)&&t.family===g).length} 项</h4><label class="choice"><input type="checkbox" data-batch-group="${esc(g)}">增加${g==='爸妈家'?'妈妈':'奶奶'}为可见人</label></div>`).join('')}${button('确认增加可见人','batch-save','primary')}`);return}
 if(name==='batch-save'){const checks=[...document.querySelectorAll('[data-batch-group]')];if(checks.some(c=>!c.checked)){toast('请为每个家庭选择可见人');return}checks.forEach(c=>tasks.filter(t=>selected.has(t.id)&&t.family===c.dataset.batchGroup).forEach(t=>{t.viewers=[...new Set([...t.viewers,t.family==='爸妈家'?'妈妈':'奶奶'])]}));sheet('本次批量结果',`<div class="notice">${selected.size} 项已增加可见人。原可见名单保留。</div><p class="note">此处模拟全部成功；部分失败和待确认流程详见交互规范。</p>${button('完成','batch-done','primary')}`);return}if(name==='batch-done'){batch=false;selected.clear();closeSheet();render();return}
 if(name==='conflict'){captureDraft();sheet('查看最新修改',`<div class="card"><h4>你的输入</h4><p>${esc(draft?.title||'读 20 分钟绘本')}</p></div><div class="card"><h4>家人已保存的版本 · 示例</h4><p>读 30 分钟绘本</p></div><p class="notice">不自动覆盖。保留本地输入后，逐项核对最新内容再保存。</p>${button('保留输入，继续核对','conflict-resolve','primary')}`);return}if(name==='conflict-resolve'){closeSheet();mode='ready';$('#state').value=mode;render();toast('演示：已保留输入，请核对后保存');return}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)action(b.dataset.action)});
document.addEventListener('input',e=>{if(e.target.id==='quick-title')action.quickDraft=e.target.value;});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='state'){if(page==='editor')captureDraft();noFamily=el.value==='no-family'||el.value==='empty'&&page==='families';mode=el.value==='no-family'?'ready':el.value;render()}if(el.id==='home-family'){family=el.value;render()}if(el.id==='progress-family'){activeFamily=el.value;render()}if(el.id==='progress-person'){document.querySelectorAll('.progress-person').forEach(c=>c.hidden=el.value!=='全部家人'&&c.dataset.person!==el.value)}if(el.id==='progress-date'){document.querySelectorAll('.progress-person').forEach(c=>c.hidden=el.value!=='2026-09-15');toast(el.value==='2026-09-15'?'已显示当天样例':'此原型仅提供 9 月 15 日进度数据')}if(el.id==='recycle-family')document.querySelectorAll('.recycle-item').forEach(c=>c.hidden=el.value!=='全部家庭'&&c.dataset.family!==el.value);if(el.id==='edit-family'){captureDraft();preferredFamily=draft.family;draft.who='自己';draft.view=draft.help=draft.remind=false;render();toast('已切换家庭，请重新选择家人')}if(el.id==='edit-who'){captureDraft();render()}if(el.id==='quick-family')preferredFamily=el.value;if(el.id==='my-reminder')reminder=el.checked;if(el.id==='permission-view'){if(!el.checked&&(draft.help||draft.remind)){const yes=window.confirm('取消查看将同时取消奶奶的代记和提醒权限。继续？');if(!yes){el.checked=true;return}}draft.view=el.checked;if(!draft.view)draft.help=draft.remind=false;permissions()}if(el.id==='permission-help')draft.help=el.checked;if(el.id==='permission-remind')draft.remind=el.checked;});
document.addEventListener('keydown',e=>{if(!$('#overlay').children.length)return;if(e.key==='Escape'){e.preventDefault();action('close')}if(e.key==='Tab'){const a=[...$('#overlay').querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea')];if(!a.length)return;const first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
$('#reset').addEventListener('click',()=>location.reload());
render();
