import { describe, expect, it } from "vitest";
import { occurrenceGroup, accessInput, permissionRows, subjectOptions, withoutViewer } from "./collaboration-draft";
import type { Roster } from "./collaboration-draft";
const roster: Roster={family:{id:"family",name:"小家",version:1,myMembershipId:"me",ownerMembershipId:"owner",authEpoch:1},members:[{id:"me",familyId:"family",name:"我",status:"active",role:"member",version:1,isMe:true},{id:"owner",familyId:"family",name:"家人",status:"active",role:"owner",version:1,isMe:false},{id:"subject",familyId:"family",name:"家人",status:"active",role:"member",version:1,isMe:false}],virtualMembers:[{id:"child",familyId:"family",name:"小宝",status:"active",version:1}]};
describe("家庭权限草稿",()=>{
  it("旧回执缺少管理身份时只保留原必要查看，不推断创建管理人",()=>{const old=permissionRows(roster,{kind:"virtual",virtualMemberId:"child"}).map(({isCreatorManager: _manager,...row})=>row);const rows=permissionRows(roster,{kind:"virtual",virtualMemberId:"child"},old,true);expect(rows.filter(row=>row.requiredViewer).map(row=>row.membershipId)).toEqual(["me","owner"]);expect(rows.every(row=>row.isCreatorManager===undefined)).toBe(true);});
  it("已有事项 A→B→C 重新计算必要查看人，不累加旧执行对象",()=>{const members=[...roster.members,...["b","c"].map(id=>({...roster.members[2],id,familyId:"family",name:id,status:"active" as const,role:"member" as const,version:1,isMe:false}))];const current={...roster,members};const original=permissionRows(current,{kind:"member",membershipId:"subject"});const second=permissionRows(current,{kind:"member",membershipId:"b"},original,true);const third=permissionRows(current,{kind:"member",membershipId:"c"},second,true);expect(third.filter(row=>row.requiredViewer).map(row=>row.membershipId)).toEqual(["me","c"]);for(const id of ["subject","b"]){const row=third.find(item=>item.membershipId===id);if(!row)throw new Error("missing member");expect(withoutViewer(row).canView).toBe(false);}});
  it("虚拟改真实时仅锁创建管理者和新执行人，旧拥有人即使是本人也可取消查看",()=>{const original=permissionRows(roster,{kind:"virtual",virtualMemberId:"child"});const ownerEditing={...roster,family:{...roster.family,myMembershipId:"owner"},members:roster.members.map(member=>({...member,isMe:member.id==="owner"}))};const rows=permissionRows(ownerEditing,{kind:"member",membershipId:"subject"},original,true);expect(rows.filter(row=>row.requiredViewer).map(row=>row.membershipId)).toEqual(["me","subject"]);const oldOwner=rows.find(row=>row.membershipId==="owner");if(!oldOwner)throw new Error("missing owner");expect(oldOwner.isMe).toBe(true);expect(withoutViewer(oldOwner).canView).toBe(false);const overlap=permissionRows(ownerEditing,{kind:"member",membershipId:"me"},rows,true);expect(overlap.filter(row=>row.requiredViewer).map(row=>row.membershipId)).toEqual(["me"]);});
  it("已归属家庭的个人历史快照按可信用户 ID 分组，代记不等于本人",()=>{const snapshot={subject:{kind:"user" as const,userId:"original-user"},canRecord:false};expect(occurrenceGroup(snapshot,"viewer-user",[])).toBe("关心一下");expect(occurrenceGroup({...snapshot,canRecord:true},"viewer-user",[])).toBe("帮家人");expect(occurrenceGroup(snapshot,"original-user",[])).toBe("我来做");expect(occurrenceGroup({subject:{kind:"member",membershipId:"me"},canRecord:false},"viewer-user",[{id:"family",name:"家",ownerName:"我",myMembershipId:"me",myRole:"member",version:1}])).toBe("我来做");});
  it("按成员 ID 而非称呼锁定真实执行人的必要查看，不自动开启提醒",()=>{const rows=permissionRows(roster,{kind:"member",membershipId:"subject"});expect(rows.find(r=>r.membershipId==="subject")).toMatchObject({requiredViewer:true,canView:true,receivesReminder:false});expect(rows.find(r=>r.membershipId==="owner")?.canView).toBe(false);expect(accessInput(rows,true).reminderMembershipIds).toEqual([]);});
  it("虚拟对象要求拥有人和创建者可见，虚拟对象不进入权限矩阵",()=>{const rows=permissionRows(roster,{kind:"virtual",virtualMemberId:"child"});expect(rows.filter(r=>r.requiredViewer).map(r=>r.membershipId)).toEqual(["me","owner"]);expect(rows.some(r=>r.membershipId==="child")).toBe(false);expect(subjectOptions(roster).at(-1)?.name).toBe("小宝 · 无账号成员");});
  it("取消查看同时清除代记和提醒，必要可见不能取消",()=>{const rows=permissionRows(roster,{kind:"self"});const optional=rows[2];const required=rows[0];if(!optional||!required)throw new Error("fixture");expect(withoutViewer({...optional,canView:true,canHelp:true,receivesReminder:true})).toMatchObject({canView:false,canHelp:false,receivesReminder:false});expect(withoutViewer(required)).toEqual(required);});
  it("本人关闭优先；保存不能替别人重新开启，本人由 remindMe 单独控制",()=>{const rows=permissionRows(roster,{kind:"self"}).map(r=>({...r,canView:true,receivesReminder:true,reminderSelfDisabled:r.membershipId==="subject"}));expect(accessInput(rows,true)).toMatchObject({reminderMembershipIds:["owner"],remindMe:true});});
});
