import { randomUUID } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { ApiRequest, PersonalActionMap, TaskDTO } from "@family-todo/contracts";
import { AppApiClient } from "./app-api-client";
import { PersonalApi, personalApi } from "./personal-api";
import { draftSchedule } from "./schedule-draft";
import { batchPayload, selectTask, retryFailedBatch } from "./batch-viewers";
afterEach(()=>vi.useRealTimers());
const fields={repeat:"daily",date:"2026-09-14",time:"",endDate:"",times:["08:00","20:00"],weekdays:[]};
describe("周期客户端",()=>{
 it("允许当天已过和未来时刻共存，周无日期与重复、超额时刻拒绝",()=>{expect(draftSchedule(fields)).toMatchObject({kind:"daily",times:["08:00","20:00"]});expect(()=>draftSchedule({...fields,repeat:"weekly"})).toThrow("至少选择");expect(()=>draftSchedule({...fields,times:["08:00","08:00"]})).toThrow("重复");expect(()=>draftSchedule({...fields,times:Array.from({length:7},(_,i)=>`0${i}:00`)})).toThrow("最多");});
 it("相同事项的多个次数只选择一个任务，个人必须明确归属",()=>{const task={id:"task",familyId:null,version:1,capabilities:{canEdit:true,canShare:true}} as TaskDTO;const first=selectTask([],task);expect(selectTask(first,task)).toEqual([]);expect(()=>batchPayload(first,[{key:"personal",name:"个人",taskIds:[task.id],targetFamilyId:"",familyIndex:0,viewers:[{id:"member",name:"家人",checked:true}],loading:false,error:""}])).toThrow("明确选择");});
 it("批量成功信封中的 pending 保留完整原请求，预算回退不恢复旧授权版本",async()=>{const tasks=[randomUUID(),randomUUID()];const requests:ApiRequest[]=[];const payload:PersonalActionMap["task.batchAddViewers"]["payload"]={items:tasks.map(taskId=>({taskId,expectedVersion:1,viewerMembershipIds:[randomUUID()]}))};const api=new PersonalApi(new AppApiClient({send:async request=>{requests.push(request);return {ok:true,requestId:request.requestId,data:requests.length===1?{complete:false,results:[{taskId:tasks[0],status:"succeeded",version:2},{taskId:tasks[1],status:"pending"}]}:requests.length===2?{complete:false,results:[{taskId:tasks[0],status:"pending"},{taskId:tasks[1],status:"succeeded",version:2}]}:{complete:true,results:tasks.map(taskId=>({taskId,status:"succeeded",version:2}))}};} }),async()=>randomUUID());await api.write("task.batchAddViewers",payload);payload.items=[];expect(api.pendingCount).toBe(1);await api.continueBatch();expect(api.batch?.result?.results[0]).toEqual({taskId:tasks[0],status:"pending"});await api.retryPending();expect(api.pendingCount).toBe(0);expect(requests).toHaveLength(3);expect(new Set(requests.map(r=>r.requestId)).size).toBe(1);expect(requests.every(r=>JSON.stringify(r.payload)===JSON.stringify(requests[0]?.payload))).toBe(true);});
 it("批量超时迟到成功不释放原始回执",async()=>{vi.useFakeTimers();const taskId=randomUUID();const requests:ApiRequest[]=[];let finish:((data:unknown)=>void)|undefined;const api=new PersonalApi(new AppApiClient({send:request=>{requests.push(request);return new Promise(resolve=>{finish=resolve;});}}),async()=>randomUUID());const first=expect(api.write("task.batchAddViewers",{items:[{taskId,expectedVersion:1,viewerMembershipIds:[]}]})).rejects.toMatchObject({retryable:true});await vi.advanceTimersByTimeAsync(10000);await first;if(!finish)throw new Error("no request");finish({ok:true,requestId:requests[0]?.requestId,data:{complete:true,results:[{taskId,status:"succeeded",version:2}]}});await Promise.resolve();expect(api.pendingCount).toBe(1);expect(api.batch?.result).toBeNull();});
 it("失败子集重试重新取版本且不包含已成功任务",async()=>{const succeeded=randomUUID(),failed=randomUUID(),family=randomUUID(),viewer=randomUUID();vi.spyOn(personalApi,"batch","get").mockReturnValue({payload:{items:[{taskId:succeeded,expectedVersion:1,viewerMembershipIds:[viewer]},{taskId:failed,expectedVersion:2,viewerMembershipIds:[viewer],targetFamilyId:family}]},result:{complete:true,results:[{taskId:succeeded,status:"succeeded",version:2},{taskId:failed,status:"failed",error:{code:"VERSION_CONFLICT",message:"版本冲突",retryable:false}}]}});const read=vi.spyOn(personalApi,"read").mockResolvedValue({task:{id:failed,version:7,familyId:null,capabilities:{canShare:true,canEdit:true}} as TaskDTO});const write=vi.spyOn(personalApi,"write").mockResolvedValue({complete:true,results:[]});await retryFailedBatch();expect(read).toHaveBeenCalledTimes(1);expect(read).toHaveBeenCalledWith("task.get",{id:failed});expect(write).toHaveBeenCalledWith("task.batchAddViewers",{items:[{taskId:failed,expectedVersion:7,viewerMembershipIds:[viewer],targetFamilyId:family}]});vi.restoreAllMocks();});

 it("批量在途续跑合并，终态后继续不会新建原操作",async()=>{const taskId=randomUUID(),requests:ApiRequest[]=[];let finish:((value:unknown)=>void)|undefined;const api=new PersonalApi(new AppApiClient({send:request=>{requests.push(request);return new Promise(resolve=>{finish=resolve;});}}),async()=>randomUUID());const first=api.write("task.batchAddViewers",{items:[{taskId,expectedVersion:1,viewerMembershipIds:[]}]});const second=api.continueBatch();const third=api.retryPending();await Promise.resolve();await Promise.resolve();expect(requests).toHaveLength(1);if(!finish)throw new Error("missing request");finish({ok:true,requestId:requests[0]?.requestId,data:{complete:true,results:[{taskId,status:"succeeded",version:2}]}});await Promise.all([first,second,third]);expect(api.pendingCount).toBe(0);await api.continueBatch();expect(requests).toHaveLength(1);expect(api.batch?.result?.complete).toBe(true);});
 it("超时旧 partial 晚于重试终态返回不能覆盖结果或恢复未决",async()=>{vi.useFakeTimers();const taskId=randomUUID(),requests:ApiRequest[]=[],finish:((value:unknown)=>void)[]=[];const api=new PersonalApi(new AppApiClient({send:request=>{requests.push(request);return new Promise(resolve=>{finish.push(resolve);});}}),async()=>randomUUID());const first=expect(api.write("task.batchAddViewers",{items:[{taskId,expectedVersion:1,viewerMembershipIds:[]}]})).rejects.toMatchObject({retryable:true});await vi.advanceTimersByTimeAsync(10000);await first;const newer=api.continueBatch();const same=api.continueBatch();await vi.advanceTimersByTimeAsync(0);expect(requests).toHaveLength(2);finish[1]?.({ok:true,requestId:requests[1]?.requestId,data:{complete:true,results:[{taskId,status:"failed",error:{code:"FORBIDDEN",message:"无权限",retryable:false}}]}});await Promise.all([newer,same]);finish[0]?.({ok:true,requestId:requests[0]?.requestId,data:{complete:false,results:[{taskId,status:"pending"}]}});await vi.advanceTimersByTimeAsync(0);expect(api.pendingCount).toBe(0);expect(api.batch?.result).toMatchObject({complete:true,results:[{status:"failed"}]});expect(requests[0]?.requestId).toBe(requests[1]?.requestId);});
 it("一次性忽略隐藏周期字段的重复和数量错误",()=>{expect(draftSchedule({...fields,repeat:"once",times:Array(7).fill("08:00"),weekdays:[],endDate:"bad"})).toEqual({kind:"once",date:"2026-09-14",time:null});});

});
