import { patchData } from "../../services/patch-data";
import { componentActions } from "../../services/component-events";
import { openFamilyTab } from "../../services/family-navigation";
import type { FamilyDTO, InvitationSummary, FamilyActionMap, Page as ApiPage } from "@family-todo/contracts";
import { isInvitationToken } from "../../shared/contracts";
import { familyApi } from "../../services/family-api";
import { collect } from "../../services/personal-lists";
import { PersonalApiError, isAccessDenied } from "../../services/personal-api";
import { back, errorMessage, instantCaption, navigationMetrics, readySession } from "../../services/personal-view";
Page({
  onComponentAction: componentActions(["accept", "copyPath", "copyToken", "create", "nameInput", "previewInvitation", "revoke", "tokenInput"]),
  data:{statusHeight:0,navHeight:44,capsuleWidth:100,status:"loading",error:"",familyId:"",family:null as FamilyDTO|null,owner:false,invitations:[] as (InvitationSummary&{expiresLabel:string;state:string})[],fromShare:false,token:"",generatedToken:"",generatedId:"",expiresLabel:"",myName:"",preview:null as FamilyActionMap["invitation.preview"]["data"]|null,writing:false,uncertain:false,joinedId:""},
  alive:true,visible:false,epoch:0,pending:null as (()=>Promise<unknown>)|null,
  onLoad(query:Record<string,string|undefined>){patchData(this, {...navigationMetrics(),familyId:query.token?"":query.familyId??"",token:query.token??"",fromShare:!!query.token});},onShow(){this.visible=true;void this.load();},onHide(){this.visible=false;this.epoch++;},onUnload(){this.alive=false;this.epoch++;patchData(this, {token:"",generatedToken:""});},back,
  async load(){if(this.pending)return;const epoch=++this.epoch;patchData(this, {error:"",...(this.data.status!=="ready"?{status:"loading",family:null,invitations:[],preview:null}:{})});try{await readySession();if(this.data.familyId){const detail=await familyApi.read("family.get",{id:this.data.familyId});const owner=detail.family.myMembershipId===detail.family.ownerMembershipId;const items=owner?(await collect<InvitationSummary,ApiPage<InvitationSummary>>(cursor=>familyApi.read("invitation.list",{familyId:detail.family.id,limit:50,...(cursor?{cursor}:{})}))).items:[];if(this.visible&&epoch===this.epoch)patchData(this, {status:"ready",family:detail.family,owner,invitations:items.map(i=>({...i,expiresLabel:instantCaption(i.expiresAt),state:i.revokedAt?"邀请已撤销":Date.parse(i.expiresAt)<=Date.now()?"邀请已过期":"邀请有效"})),...(!owner?{generatedToken:"",generatedId:""}:{})});}else{if(this.visible&&epoch===this.epoch)patchData(this, {status:"ready"});if(this.data.token)await this.previewInvitation();}}catch(error){if(this.visible&&epoch===this.epoch)patchData(this, {status:"error",error:errorMessage(error),family:null,invitations:[],preview:null,generatedToken:""});}},
  tokenInput(e:WechatMiniprogram.Input){if(!this.pending)patchData(this, {token:e.detail.value.trim(),preview:null,joinedId:""});},nameInput(e:WechatMiniprogram.Input){patchData(this, {myName:e.detail.value});},
  async previewInvitation(){if(this.pending)return;if(!isInvitationToken(this.data.token)){patchData(this, {error:"请填写完整的 22 位邀请口令。",preview:null});return;}const epoch=++this.epoch;const token=this.data.token;patchData(this, {status:"loading",preview:null,error:""});try{const preview=await familyApi.read("invitation.preview",{token});if(this.visible&&epoch===this.epoch)patchData(this, {status:"ready",preview,expiresLabel:instantCaption(preview.expiresAt)});}catch(error){if(this.visible&&epoch===this.epoch)patchData(this, {status:"ready",error:errorMessage(error),preview:null});}},
  async run(run:()=>Promise<unknown>){if(this.data.writing)return;this.pending??=run;patchData(this, {writing:true,error:""});try{await this.pending();this.pending=null;if(this.alive)patchData(this, {uncertain:false});}catch(error){const uncertain=error instanceof PersonalApiError&&error.retryable;if(!uncertain)this.pending=null;if(this.alive){if(isAccessDenied(error)){this.epoch++;patchData(this, {status:"error",family:null,invitations:[],owner:false,token:"",generatedToken:"",generatedId:"",preview:null,myName:"",expiresLabel:"",joinedId:""});}patchData(this, {uncertain,error:errorMessage(error)});}}finally{if(this.alive)patchData(this, {writing:false});}},async retryWrite(){if(this.pending){await this.run(this.pending);if(!this.pending&&this.data.familyId)await this.load();}},
  async create(){const family=this.data.family;if(!family||!this.data.owner)return;const payload={familyId:family.id,expectedFamilyVersion:family.version};await this.run(async()=>{const result=await familyApi.write("invitation.create",payload);if(this.alive)patchData(this, {generatedToken:result.token,generatedId:result.id,expiresLabel:instantCaption(result.expiresAt)});});if(!this.pending)await this.load();},
  async revoke(e:WechatMiniprogram.TouchEvent){const invitation=this.data.invitations.find(i=>i.id===e.currentTarget.dataset.id);if(!invitation||!this.data.owner)return;const answer=await wx.showModal({title:"撤销这份邀请？",content:"已加入的成员不受影响；其他人不能再通过它加入。",confirmText:"撤销邀请"});if(!answer.confirm||!this.visible)return;const payload={id:invitation.id,expectedVersion:invitation.version};await this.run(async()=>{await familyApi.write("invitation.revoke",payload);if(this.alive&&this.data.generatedId===invitation.id)patchData(this, {generatedToken:"",generatedId:""});});if(!this.pending)await this.load();},
  copyToken(){if(this.data.generatedToken)void wx.setClipboardData({data:this.data.generatedToken});},
  copyPath(){if(this.data.generatedToken)void wx.setClipboardData({data:`/pages/invitation/index?token=${encodeURIComponent(this.data.generatedToken)}`});},
  onShareAppMessage(){
    const token=this.data.generatedToken || (this.data.preview ? this.data.token : "");
    const familyName=this.data.family?.name ?? this.data.preview?.familyName;
    return {title:familyName ? `邀请你加入「${familyName}」` : "一起照应日常的小事",path:isInvitationToken(token)?`/pages/invitation/index?token=${encodeURIComponent(token)}`:"/pages/invitation/index"};
  },
  async accept(){if(!this.data.preview||!isInvitationToken(this.data.token))return;const myName=this.data.myName.trim();if(!myName||[...myName].length>12){patchData(this, {error:"请填写 1–12 个字的家庭称呼。"});return;}const payload={token:this.data.token,myName};await this.run(async()=>{const result=await familyApi.write("invitation.accept",payload);if(this.alive)patchData(this, {joinedId:result.familyId,token:"",preview:null});});},
  openFamily(){if(this.data.joinedId)openFamilyTab(this.data.joinedId);},
});
