import type { FamilySummary, MemberProgress, ResolvedSubject } from "@family-todo/contracts";
import { personalApi, PersonalApiError, isAccessDenied } from "../../services/personal-api";
import { familyApi, listFamilies } from "../../services/family-api";
import { back, dateAt, dateCaption, errorMessage, navigationMetrics, readySession } from "../../services/personal-view";
function meter(percent:number):string {return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 34 34"><circle cx="17" cy="17" r="14" fill="none" stroke="#eeedf4" stroke-width="2.5"/><circle cx="17" cy="17" r="14" fill="none" stroke="#74629b" stroke-width="2.5" stroke-dasharray="${percent*0.8796} 87.96" transform="rotate(-90 17 17)"/></svg>`)}`;}
function subjectKey(subject:ResolvedSubject|undefined){return subject?JSON.stringify(subject):"all";}
type Filter={name:string;subject?:ResolvedSubject};
Page({
  data:{statusHeight:0,navHeight:44,capsuleWidth:100,status:"loading",error:"",families:[] as FamilySummary[],familyId:"",familyName:"",date:"",dateLabel:"",filters:[{name:"全部执行对象"}] as Filter[],filterNames:["全部执行对象"],subjectIndex:0,members:null as (MemberProgress&{key:string;initial:string;percent:number;meter:string})[]|null,memberCaption:"",portraits:[] as string[],loading:false},
  alive:true,visible:false,epoch:0,cursor:undefined as string|undefined,
  onLoad(){this.setData(navigationMetrics());},onShow(){this.visible=true;void this.load();},onHide(){this.stop();},onUnload(){this.alive=false;this.stop();},
  stop(){this.visible=false;this.epoch++;this.cursor=undefined;this.setData({members:null,filters:[],filterNames:[],portraits:[],memberCaption:""});},back,
  manage(){wx.navigateTo({url:"/pages/families/index"});},
  async load(){const epoch=++this.epoch;this.cursor=undefined;this.setData({status:"loading",members:null,error:"",loading:true});try{await readySession();const families=await listFamilies();if(!this.visible||epoch!==this.epoch)return;const family=families.items.find(f=>f.id===this.data.familyId)??families.items[0];this.setData({families:families.items});if(!family){this.setData({status:"empty",loading:false,familyId:"",familyName:"",members:[],filters:[],filterNames:[],portraits:[],memberCaption:""});return;}this.setData({familyId:family.id,familyName:family.name,date:this.data.date||dateAt(families.last.asOf)});await this.loadScope(epoch);}catch(error){this.fail(error,epoch);}},
  async loadScope(epoch:number){this.cursor=undefined;this.setData({members:null,filters:[],filterNames:[],portraits:[],memberCaption:"",status:"loading",loading:true,error:""});try{const roster=await familyApi.read("family.get",{id:this.data.familyId});if(!this.visible||epoch!==this.epoch)return;const filters:Filter[]=[{name:"全部执行对象"},...roster.members.map(m=>({name:m.name,subject:{kind:"member" as const,membershipId:m.id}})),...roster.virtualMembers.map(m=>({name:`${m.name} · 无账号成员`,subject:{kind:"virtual" as const,virtualMemberId:m.id}}))];this.setData({filters,filterNames:filters.map(f=>f.name),subjectIndex:0,portraits:[...roster.members,...roster.virtualMembers].slice(0,4).map(m=>m.name.slice(0,1)),memberCaption:`${roster.members.length} 位家人 · ${roster.virtualMembers.length} 位无账号成员`});await this.query(epoch);}catch(error){this.fail(error,epoch);}},
  async query(epoch:number){const familyId=this.data.familyId,date=this.data.date,subject=this.data.filters[this.data.subjectIndex]?.subject;let restarted=false;this.setData({members:null,status:"loading",loading:true,error:"",dateLabel:dateCaption(date)});while(this.visible&&epoch===this.epoch){try{const result=await personalApi.read("progress.get",{familyId,date,...(subject?{subject}:{}),...(this.cursor?{cursor:this.cursor}:{})});if(!this.visible||epoch!==this.epoch)return;if(result.complete&&result.members!==null){this.cursor=undefined;const filters=[...this.data.filters];for(const member of result.members){if(!filters.some(f=>subjectKey(f.subject)===subjectKey(member.subject)))filters.push({name:member.name,subject:member.subject});}this.setData({filters,filterNames:filters.map(f=>f.name),members:result.members.map((member,index)=>({...member,key:String(index),initial:member.name.slice(0,1),meter:meter(member.denominator?member.completed/member.denominator*100:0),percent:member.denominator?member.completed/member.denominator*100:0})),status:result.members.length?"ready":"empty",loading:false});return;}if(!result.nextCursor)throw new Error("进度未完整加载，请重试。");this.cursor=result.nextCursor;}catch(error){if(!this.visible||epoch!==this.epoch)return;if(error instanceof PersonalApiError&&error.code==="CURSOR_EXPIRED"&&!restarted){this.cursor=undefined;restarted=true;continue;}this.fail(error,epoch);return;}}},
  fail(error:unknown,epoch:number){if(!this.visible||epoch!==this.epoch)return;const denied=isAccessDenied(error);if(denied)this.cursor=undefined;this.setData({status:"error",members:null,error:errorMessage(error),loading:false,...(denied?{families:this.data.families.filter(f=>f.id!==this.data.familyId),familyId:"",familyName:"",filters:[],filterNames:[],portraits:[],memberCaption:""}:{})});},
  retry(){if(!this.data.familyId||!this.data.filters.length){void this.load();return;}void this.query(++this.epoch);},
  familyChange(e:WechatMiniprogram.TouchEvent){const family=this.data.families.find(f=>f.id===e.currentTarget.dataset.id);if(!family)return;const epoch=++this.epoch;this.setData({familyId:family.id,familyName:family.name,subjectIndex:0});void this.loadScope(epoch);},
  dateChange(e:WechatMiniprogram.PickerChange){if(typeof e.detail.value!=="string"||!this.data.familyId)return;this.setData({date:e.detail.value});this.cursor=undefined;const epoch=++this.epoch;if(!this.data.filters.length)void this.loadScope(epoch);else void this.query(epoch);},
  subjectChange(e:WechatMiniprogram.PickerChange){this.setData({subjectIndex:Number(e.detail.value)});this.cursor=undefined;void this.query(++this.epoch);},
});
