import { familyProgress } from "../../services/family-progress";
import { patchData } from "../../services/patch-data";
import { componentActions } from "../../services/component-events";
import { openFamilyTab } from "../../services/family-navigation";
import type { FamilySummary, MemberProgress, ResolvedSubject } from "@family-todo/contracts";
import { personalApi, PersonalApiError, isAccessDenied } from "../../services/personal-api";
import { familyApi, listFamilies } from "../../services/family-api";
import { ListCancelledError, ListContinuationError, listMetricsConfigured, metricRequest, startListMetric } from "../../services/list-metrics";
import { back, dateAt, dateCaption, errorMessage, navigationMetrics, readySession } from "../../services/personal-view";
function meter(percent:number):string {return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 34 34"><circle cx="17" cy="17" r="14" fill="none" stroke="#eeedf4" stroke-width="2.5"/><circle cx="17" cy="17" r="14" fill="none" stroke="#74629b" stroke-width="2.5" stroke-dasharray="${percent*0.8796} 87.96" transform="rotate(-90 17 17)"/></svg>`)}`;}
function subjectKey(subject:ResolvedSubject|undefined){return subject?JSON.stringify(subject):"all";}
type Filter={name:string;subject?:ResolvedSubject};
Page({
  onComponentAction: componentActions(["familyChange"]),
  data:{statusHeight:0,navHeight:44,capsuleWidth:100,status:"loading",error:"",families:[] as FamilySummary[],familyId:"",familyName:"",date:"",dateLabel:"",filters:[{name:"全部执行对象"}] as Filter[],filterNames:["全部执行对象"],subjectIndex:0,members:null as (MemberProgress&{key:string;initial:string;percent:number;meter:string})[]|null,memberCaption:"",portraits:[] as string[],loading:false},
  alive:true,visible:false,epoch:0,cursor:undefined as string|undefined,
  onLoad(){patchData(this, navigationMetrics());},onShow(){this.visible=true;void this.load();},onHide(){this.stop();},onUnload(){this.alive=false;this.stop();},
  stop(){this.visible=false;this.epoch++;this.cursor=undefined;patchData(this, {members:null,filters:[],filterNames:[],portraits:[],memberCaption:""});},back,
  manage(){openFamilyTab();},
  async load(){const epoch=++this.epoch;this.cursor=undefined;patchData(this, {error:"",...(this.data.members===null?{status:"loading",loading:true}:{})});try{await readySession();const families=await listFamilies();if(!this.visible||epoch!==this.epoch)return;const family=families.items.find(f=>f.id===this.data.familyId)??families.items[0];patchData(this, {families:families.items});if(!family){patchData(this, {status:"empty",loading:false,familyId:"",familyName:"",members:[],filters:[],filterNames:[],portraits:[],memberCaption:""});return;}patchData(this, {familyId:family.id,familyName:family.name,date:this.data.date||dateAt(families.last.asOf),...(family.id!==this.data.familyId?{members:null}:{})});await this.loadScope(epoch);}catch(error){this.fail(error,epoch);}},
  async loadScope(epoch:number){this.cursor=undefined;patchData(this, {error:"",...(this.data.members===null?{filters:[],filterNames:[],portraits:[],memberCaption:"",status:"loading",loading:true}:{})});try{const date=this.data.date;const [roster,members]=await Promise.all([familyApi.read("family.get",{id:this.data.familyId}),familyProgress(this.data.familyId,date,()=>this.visible&&epoch===this.epoch)]);if(!this.visible||epoch!==this.epoch)return;const filters:Filter[]=[{name:"全部执行对象"},...roster.members.map(m=>({name:m.name,subject:{kind:"member" as const,membershipId:m.id}})),...roster.virtualMembers.map(m=>({name:`${m.name} · 无账号成员`,subject:{kind:"virtual" as const,virtualMemberId:m.id}}))];patchData(this, {filters,filterNames:filters.map(f=>f.name),subjectIndex:0,portraits:[...roster.members,...roster.virtualMembers].slice(0,4).map(m=>m.name.slice(0,1)),memberCaption:`${roster.members.length} 位家人 · ${roster.virtualMembers.length} 位无账号成员`});patchData(this, {dateLabel:dateCaption(date)});this.applyProgress(members);}catch(error){this.fail(error,epoch);}},
  async query(epoch:number){const familyId=this.data.familyId,date=this.data.date,subject=this.data.filters[this.data.subjectIndex]?.subject;let restarted=false;patchData(this, {error:"",dateLabel:dateCaption(date),...(this.data.members===null?{status:"loading",loading:true}:{})});const metric=listMetricsConfigured()?startListMetric("progress.get"):undefined;while(this.visible&&epoch===this.epoch){try{const payload={familyId,date,...(subject?{subject}:{}),...(this.cursor?{cursor:this.cursor}:{})};const result=await metricRequest(metric,observer=>observer?personalApi.read("progress.get",payload,observer):personalApi.read("progress.get",payload));if(!this.visible||epoch!==this.epoch){metric?.finishError(new ListCancelledError());return;}metric?.page(result.members?.length??0,!result.complete,"members");if(result.complete&&result.members!==null){this.cursor=undefined;metric?.finish("success");this.applyProgress(result.members);return;}if(!result.nextCursor)throw new ListContinuationError("进度未完整加载，请重试。");this.cursor=result.nextCursor;}catch(error){if(!this.visible||epoch!==this.epoch){metric?.finishError(new ListCancelledError());return;}if(error instanceof PersonalApiError&&error.code==="CURSOR_EXPIRED"&&!restarted){this.cursor=undefined;restarted=true;metric?.restart();continue;}metric?.finishError(error);this.fail(error,epoch);return;}}metric?.finishError(new ListCancelledError());},
  applyProgress(members:MemberProgress[]){const filters=[...this.data.filters];for(const member of members){if(!filters.some(f=>subjectKey(f.subject)===subjectKey(member.subject)))filters.push({name:member.name,subject:member.subject});}patchData(this, {filters,filterNames:filters.map(f=>f.name),members:members.map(member=>({...member,key:subjectKey(member.subject),initial:member.name.slice(0,1),meter:meter(member.denominator?member.completed/member.denominator*100:0),percent:member.denominator?member.completed/member.denominator*100:0})),status:members.length?"ready":"empty",loading:false});},
  fail(error:unknown,epoch:number){if(!this.visible||epoch!==this.epoch)return;const denied=isAccessDenied(error);if(denied)this.cursor=undefined;patchData(this, {status:"error",members:null,error:errorMessage(error),loading:false,...(denied?{families:this.data.families.filter(f=>f.id!==this.data.familyId),familyId:"",familyName:"",filters:[],filterNames:[],portraits:[],memberCaption:""}:{})});},
  retry(){if(!this.data.familyId||!this.data.filters.length){void this.load();return;}void this.query(++this.epoch);},
  familyChange(e:WechatMiniprogram.TouchEvent){const family=this.data.families.find(f=>f.id===e.currentTarget.dataset.id);if(!family)return;const epoch=++this.epoch;patchData(this, {familyId:family.id,familyName:family.name,subjectIndex:0,members:null});void this.loadScope(epoch);},
  dateChange(e:WechatMiniprogram.PickerChange){if(typeof e.detail.value!=="string"||!this.data.familyId)return;patchData(this, {date:e.detail.value,members:null});this.cursor=undefined;const epoch=++this.epoch;if(!this.data.filters.length)void this.loadScope(epoch);else void this.query(epoch);},
  subjectChange(e:WechatMiniprogram.PickerChange){patchData(this, {subjectIndex:Number(e.detail.value),members:null});this.cursor=undefined;void this.query(++this.epoch);},
});
